import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';
import { usePaperStore } from '../../services/paperStore';
import { PaperConfiguration, Question } from '../../types';

// Register a standard font (optional, using default Helvetica for now)
// Font.register({ family: 'Roboto', src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-light-webfont.ttf' });

const styles = StyleSheet.create({
    page: { padding: 40, fontFamily: 'Helvetica' },
    header: { marginBottom: 20, borderBottom: '1pt solid #ccc', paddingBottom: 10 },
    title: { fontSize: 18, textAlign: 'center', fontWeight: 'bold', marginBottom: 5 },
    subtitle: { fontSize: 12, textAlign: 'center', color: '#666' },
    metaRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10, fontSize: 10, color: '#444' },

    sectionTitle: { fontSize: 14, fontWeight: 'bold', marginTop: 15, marginBottom: 10, textTransform: 'uppercase', backgroundColor: '#f0f0f0', padding: 4 },

    questionContainer: { marginBottom: 10 },
    questionText: { fontSize: 11, marginBottom: 4 },
    questionMeta: { fontSize: 9, color: '#888', marginBottom: 2 },

    optionsGrid: { marginLeft: 15, marginTop: 4 },
    optionRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 2 },
    optionText: { fontSize: 10 },

    // Modern specific
    modernHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 30, borderBottom: '2pt solid #4F46E5', paddingBottom: 15 },
    modernTitle: { fontSize: 24, color: '#111827', fontWeight: 'bold' },
    modernMeta: { fontSize: 10, color: '#6B7280' },
    modernSection: { fontSize: 12, color: '#4F46E5', fontWeight: 'bold', marginTop: 20, marginBottom: 12, letterSpacing: 1 },

    // Minimal specific
    minimalPage: { padding: 50, fontFamily: 'Times-Roman' },
    minimalTitle: { fontSize: 16, textAlign: 'left', marginBottom: 30, textDecoration: 'underline' },
});

interface TemplateProps {
    config: PaperConfiguration;
}

// --- 1. Classic Template (Dense, Traditional) ---
export const ClassicTemplate: React.FC<TemplateProps> = ({ config }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>{config.title}</Text>
                {config.subtitle && <Text style={styles.subtitle}>{config.subtitle}</Text>}
                <View style={styles.metaRow}>
                    <Text>Course: {config.course || 'N/A'}</Text>
                    <Text>Time: {config.time || '3 Hrs'}</Text>
                    <Text>Marks: {config.marks || '100'}</Text>
                </View>
            </View>

            {config.sections.map((section, sIdx) => (
                <View key={section.id}>
                    {section.questions.length > 0 && (
                        <Text style={styles.sectionTitle}>{section.title} {section.marks ? `(${section.marks} Marks)` : ''}</Text>
                    )}
                    {section.questions.map((q, qIdx) => (
                        <View key={q.id} style={styles.questionContainer}>
                            <Text style={styles.questionText}>{qIdx + 1}. {q.question_eng}  <Text style={{ fontSize: 9, color: '#666' }}>[{q.marks || 1}M]</Text></Text>
                            {q.question_hin && <Text style={{ ...styles.questionText, fontStyle: 'italic', fontSize: 10, color: '#444' }}>{q.question_hin}</Text>}

                            <View style={styles.optionsGrid}>
                                <View style={styles.optionRow}>
                                    <Text style={styles.optionText}>(a) {q.option1_eng}</Text>
                                    <Text style={styles.optionText}>(b) {q.option2_eng}</Text>
                                </View>
                                <View style={styles.optionRow}>
                                    <Text style={styles.optionText}>(c) {q.option3_eng}</Text>
                                    <Text style={styles.optionText}>(d) {q.option4_eng}</Text>
                                </View>
                            </View>
                        </View>
                    ))}
                </View>
            ))}

            <Text style={{ position: 'absolute', bottom: 30, right: 40, fontSize: 9, color: '#ccc' }}>Generated by Q-Bank Pro</Text>
        </Page>
    </Document>
);

// --- 2. Modern Template (Airy, Clean) ---
export const ModernTemplate: React.FC<TemplateProps> = ({ config }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.modernHeader}>
                <View>
                    <Text style={styles.modernTitle}>{config.title}</Text>
                    {config.subtitle && <Text style={{ fontSize: 12, color: '#6B7280', marginTop: 4 }}>{config.subtitle}</Text>}
                </View>
                <View style={{ alignItems: 'flex-end' }}>
                    <Text style={styles.modernMeta}>{config.course || 'Examination'}</Text>
                    <Text style={styles.modernMeta}>{config.time || '3 Hours'} • {config.marks || '100'} Marks</Text>
                </View>
            </View>

            {config.sections.map((section, sIdx) => (
                <View key={section.id}>
                    {section.questions.length > 0 && (
                        <Text style={styles.modernSection}>{section.title}</Text>
                    )}
                    {section.questions.map((q, qIdx) => (
                        <View key={q.id} style={{ marginBottom: 15, padding: 10, backgroundColor: '#FAFAFA', borderRadius: 4 }}>
                            <Text style={{ ...styles.questionText, fontSize: 10, color: '#6B7280', marginBottom: 2 }}>Question {qIdx + 1} • {q.cognitive_level || 'Knowledge'} • {q.marks || 1} Marks</Text>
                            <Text style={{ ...styles.questionText, fontSize: 12, marginBottom: 8 }}>{q.question_eng}</Text>

                            <View style={{ marginLeft: 10 }}>
                                <Text style={{ fontSize: 10, marginBottom: 4 }}>• {q.option1_eng}</Text>
                                <Text style={{ fontSize: 10, marginBottom: 4 }}>• {q.option2_eng}</Text>
                                <Text style={{ fontSize: 10, marginBottom: 4 }}>• {q.option3_eng}</Text>
                                <Text style={{ fontSize: 10, marginBottom: 4 }}>• {q.option4_eng}</Text>
                            </View>
                        </View>
                    ))}
                </View>
            ))}
        </Page>
    </Document>
);

// --- 3. Minimal Template (Simple, Text-focused) ---
export const MinimalTemplate: React.FC<TemplateProps> = ({ config }) => (
    <Document>
        <Page size="A4" style={styles.minimalPage}>
            <Text style={styles.minimalTitle}>{config.title}  |  {config.course || ''}</Text>

            {config.sections.map((section) => (
                <View key={section.id} style={{ marginBottom: 20 }}>
                    {section.questions.length > 0 && <Text style={{ fontSize: 12, fontWeight: 'bold', marginBottom: 10, textDecoration: 'underline' }}>{section.title}</Text>}
                    {section.questions.map((q, i) => (
                        <View key={q.id} style={{ marginBottom: 8, flexDirection: 'row' }}>
                            <Text style={{ width: 20, fontSize: 11 }}>{i + 1}.</Text>
                            <View style={{ flex: 1 }}>
                                <Text style={{ fontSize: 11, marginBottom: 4 }}>{q.question_eng}</Text>
                                <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
                                    <Text style={{ fontSize: 10, width: '50%' }}>a) {q.option1_eng}</Text>
                                    <Text style={{ fontSize: 10, width: '50%' }}>b) {q.option2_eng}</Text>
                                    <Text style={{ fontSize: 10, width: '50%' }}>c) {q.option3_eng}</Text>
                                    <Text style={{ fontSize: 10, width: '50%' }}>d) {q.option4_eng}</Text>
                                </View>
                            </View>
                            <Text style={{ fontSize: 10, width: 30, textAlign: 'right' }}>[{q.marks}]</Text>
                        </View>
                    ))}
                </View>
            ))}
        </Page>
    </Document>
);
