"use client";

import React, { useState } from 'react';
import { Book, Layers, Sparkles, Download, ChevronRight, CheckCircle, RefreshCw, ChevronDown } from 'lucide-react';

interface BookConfig {
    title: string;
    subject: string;
    audience: string;
    topics: string;
}

interface BookStructure {
    title: string;
    chapters: {
        title: string;
        sections: string[];
    }[];
}

export const BookGenerator: React.FC = () => {
    const [step, setStep] = useState<'config' | 'preview' | 'generating'>('config');
    const [config, setConfig] = useState<BookConfig>({
        title: '',
        subject: 'Mathematics',
        audience: 'Class 9-10',
        topics: ''
    });
    const [structure, setStructure] = useState<BookStructure | null>(null);
    const [generatedContent, setGeneratedContent] = useState<string>('');
    const [progress, setProgress] = useState(0);
    const [aiModel, setAiModel] = useState('gemini-pro');

    const subjects = [
        'Mathematics', 'Physics', 'Chemistry', 'Biology', 
        'English', 'Hindi', 'Social Science', 'Computer Science'
    ];

    const aiModels = [
        { id: 'gemini-pro', name: 'Gemini Pro', provider: 'Google' },
        { id: 'gpt-4', name: 'GPT-4', provider: 'OpenAI' },
        { id: 'claude-3', name: 'Claude 3', provider: 'Anthropic' }
    ];

    const handleGenerateStructure = async () => {
        if (!config.title || !config.topics) return;
        setStep('generating');
        try {
            // Simulate AI structure generation
            await new Promise(resolve => setTimeout(resolve, 1500));
            
            const mockStructure: BookStructure = {
                title: config.title,
                chapters: [
                    {
                        title: "Introduction to " + config.subject,
                        sections: ["Basic Concepts", "Fundamental Principles", "Real-world Applications"]
                    },
                    {
                        title: "Core Topics",
                        sections: ["Advanced Concepts", "Problem Solving", "Practice Exercises"]
                    },
                    {
                        title: "Review and Assessment",
                        sections: ["Chapter Summary", "Key Points", "Self Assessment"]
                    }
                ]
            };
            
            setStructure(mockStructure);
            setStep('preview');
        } catch (error) {
            alert(`Failed to generate structure.`);
            setStep('config');
        }
    };

    const handleGenerateFullBook = async () => {
        if (!structure) return;
        setStep('generating');
        let fullContent = `# ${structure.title}\n\n`;

        for (let i = 0; i < structure.chapters.length; i++) {
            const chapter = structure.chapters[i];
            setProgress(((i) / structure.chapters.length) * 100);

            try {
                // Simulate content generation
                await new Promise(resolve => setTimeout(resolve, 800));
                
                fullContent += `\n\n## Chapter ${i + 1}: ${chapter.title}\n\n`;
                chapter.sections.forEach((section, idx) => {
                    fullContent += `\n### ${section}\n\n`;
                    fullContent += `This is detailed content for the ${section} section. In a real implementation, this would be generated by AI based on the chapter structure and learning objectives.\n\n`;
                });
                
                setGeneratedContent(fullContent);
                setProgress(((i + 1) / structure.chapters.length) * 100);
            } catch (error) {
                console.error('Failed to generate chapter:', error);
            }
        }
        setProgress(100);
    };

    const handleDownloadPDF = () => {
        // In a real implementation, this would generate a proper PDF
        const blob = new Blob([generatedContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${config.title.replace(/\s+/g, '_')}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const resetGenerator = () => {
        setStep('config');
        setConfig({ title: '', subject: 'Mathematics', audience: 'Class 9-10', topics: '' });
        setStructure(null);
        setGeneratedContent('');
        setProgress(0);
    };

    return (
        <div className="w-full max-w-6xl mx-auto p-6 space-y-8">
            <div className="text-center space-y-6 mb-12">
                <div className="inline-flex items-center justify-center p-4 bg-gradient-to-br from-purple-500/20 via-purple-500/10 to-indigo-500/20 text-purple-600 rounded-3xl mb-4 ring-2 ring-purple-500/20 shadow-lg">
                    <div className="p-3 bg-gradient-to-br from-purple-500 to-indigo-500 rounded-2xl">
                        <Book size={28} className="text-white" />
                    </div>
                </div>
                <h2 className="text-4xl font-black text-foreground bg-gradient-to-r from-purple-500 to-indigo-500 bg-clip-text text-transparent tracking-tight">AI Book Generator</h2>
                <p className="text-muted-foreground font-medium text-lg max-w-2xl mx-auto">
                    Create comprehensive educational books with AI-powered content generation. From structure planning to full content creation.
                </p>
            </div>

            <div className="bg-white rounded-2xl border border-border p-8 shadow-lg hover:shadow-xl transition-shadow duration-300">
                {step === 'config' && (
                    <div className="space-y-8">
                        <h3 className="text-2xl font-bold text-foreground mb-8 flex items-center gap-3">
                            <div className="p-3 bg-gradient-to-br from-purple-500/20 to-purple-500/5 rounded-xl">
                                <Layers className="h-6 w-6 text-purple-500" />
                            </div>
                            Book Configuration
                        </h3>
                        
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div className="space-y-4">
                                <div>
                                    <label className="block text-sm font-medium text-foreground mb-2">
                                        Book Title *
                                    </label>
                                    <input
                                        type="text"
                                        value={config.title}
                                        onChange={(e) => setConfig({...config, title: e.target.value})}
                                        placeholder="Enter book title"
                                        className="w-full p-3 border border-border rounded-lg bg-background text-foreground focus:ring-2 focus:ring-primary focus:border-primary"
                                    />
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-foreground mb-2">
                                        Subject
                                    </label>
                                    <select
                                        value={config.subject}
                                        onChange={(e) => setConfig({...config, subject: e.target.value})}
                                        className="w-full p-3 border border-border rounded-lg bg-background text-foreground focus:ring-2 focus:ring-primary focus:border-primary"
                                    >
                                        {subjects.map(subject => (
                                            <option key={subject} value={subject}>{subject}</option>
                                        ))}
                                    </select>
                                </div>
                            </div>

                            <div className="space-y-4">
                                <div>
                                    <label className="block text-sm font-medium text-foreground mb-2">
                                        Target Audience
                                    </label>
                                    <input
                                        type="text"
                                        value={config.audience}
                                        onChange={(e) => setConfig({...config, audience: e.target.value})}
                                        placeholder="e.g., Class 9-10, JEE Aspirants"
                                        className="w-full p-3 border border-border rounded-lg bg-background text-foreground focus:ring-2 focus:ring-primary focus:border-primary"
                                    />
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-foreground mb-2">
                                        Key Topics (comma-separated) *
                                    </label>
                                    <input
                                        type="text"
                                        value={config.topics}
                                        onChange={(e) => setConfig({...config, topics: e.target.value})}
                                        placeholder="e.g., Algebra, Geometry, Calculus"
                                        className="w-full p-3 border border-border rounded-lg bg-background text-foreground focus:ring-2 focus:ring-primary focus:border-primary"
                                    />
                                </div>
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-medium text-foreground mb-2">
                                AI Model
                            </label>
                            <select
                                value={aiModel}
                                onChange={(e) => setAiModel(e.target.value)}
                                className="w-full p-3 border border-border rounded-lg bg-background text-foreground focus:ring-2 focus:ring-primary focus:border-primary max-w-md"
                            >
                                {aiModels.map(model => (
                                    <option key={model.id} value={model.id}>
                                        {model.name} ({model.provider})
                                    </option>
                                ))}
                            </select>
                        </div>

                        <div className="flex gap-4">
                            <button
                                onClick={handleGenerateStructure}
                                disabled={!config.title || !config.topics}
                                className="bg-gradient-to-r from-purple-500 to-indigo-500 text-white px-8 py-4 rounded-xl font-bold hover:from-purple-500/90 hover:to-indigo-500/90 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-3 shadow-lg hover:shadow-xl disabled:hover:shadow-lg"
                            >
                                <Sparkles className="h-5 w-5" />
                                <span className="text-lg">Generate Structure</span>
                            </button>
                            
                            <button
                                onClick={resetGenerator}
                                className="bg-muted text-foreground px-6 py-3 rounded-lg font-semibold hover:bg-muted/80 transition-colors"
                            >
                                Reset
                            </button>
                        </div>
                    </div>
                )}

                {step === 'generating' && (
                    <div className="text-center space-y-6 py-12">
                        <RefreshCw className="h-12 w-12 text-primary mx-auto animate-spin" />
                        <div>
                            <h3 className="text-xl font-bold text-foreground mb-2">Generating Content</h3>
                            <p className="text-muted-foreground">AI is creating your educational book...</p>
                        </div>
                        <div className="w-full max-w-md mx-auto">
                            <div className="w-full bg-muted rounded-full h-2.5">
                                <div 
                                    className="bg-primary h-2.5 rounded-full transition-all duration-300"
                                    style={{ width: `${progress}%` }}
                                ></div>
                            </div>
                            <p className="text-sm text-muted-foreground mt-2">{Math.round(progress)}% complete</p>
                        </div>
                    </div>
                )}

                {step === 'preview' && structure && (
                    <div className="space-y-6">
                        <div className="flex items-center justify-between">
                            <h3 className="text-xl font-bold text-foreground">Generated Structure</h3>
                            <div className="flex gap-3">
                                <button
                                    onClick={handleGenerateFullBook}
                                    className="bg-primary text-primary-foreground px-6 py-2 rounded-lg font-semibold hover:bg-primary/90 transition-colors flex items-center gap-2"
                                >
                                    <Layers className="h-4 w-4" />
                                    Generate Full Book
                                </button>
                                <button
                                    onClick={resetGenerator}
                                    className="bg-muted text-foreground px-6 py-2 rounded-lg font-semibold hover:bg-muted/80 transition-colors"
                                >
                                    Back to Config
                                </button>
                            </div>
                        </div>

                        <div className="bg-muted p-6 rounded-lg">
                            <h4 className="font-bold text-lg mb-4">{structure.title}</h4>
                            <div className="space-y-4">
                                {structure.chapters.map((chapter, index) => (
                                    <div key={index} className="border-l-4 border-primary pl-4">
                                        <h5 className="font-semibold text-foreground">{chapter.title}</h5>
                                        <div className="mt-2 space-y-1">
                                            {chapter.sections.map((section, secIndex) => (
                                                <div key={secIndex} className="flex items-center gap-2 text-sm text-muted-foreground">
                                                    <ChevronRight className="h-3 w-3" />
                                                    {section}
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                )}
            </div>

            {generatedContent && (
                <div className="bg-white rounded-2xl border border-border p-6 shadow-sm">
                    <div className="flex items-center justify-between mb-4">
                        <h3 className="text-xl font-bold text-foreground">Generated Content</h3>
                        <button
                            onClick={handleDownloadPDF}
                            className="bg-primary text-primary-foreground px-4 py-2 rounded-lg font-semibold hover:bg-primary/90 transition-colors flex items-center gap-2"
                        >
                            <Download className="h-4 w-4" />
                            Download
                        </button>
                    </div>
                    
                    <div className="bg-muted p-4 rounded-lg max-h-96 overflow-y-auto">
                        <pre className="text-sm text-foreground whitespace-pre-wrap">
                            {generatedContent}
                        </pre>
                    </div>
                </div>
            )}
        </div>
    );
};