"use client";

import React, { useState, useMemo, useEffect } from 'react';
import {
  ArrowLeft, FileText, Columns, Type, Image as ImageIcon, AlignLeft,
  Settings, ChevronDown, Download, FileJson, Table2, FileSpreadsheet,
  BookOpen, Shield, Plus, Trash2, Layers, CheckCircle, Palette,
  Clock, User, Calendar, GraduationCap, Printer, ZoomIn, ZoomOut,
  Presentation, Eye, Monitor, Sun, Moon, Paintbrush
} from 'lucide-react';
import { Question, QuestionSet } from '../types';
import { generateQuestionSetPDF, PDFExportConfig } from '../utils/pdfGenerator';
import { generateQuestionSetPPT } from '../utils/pptGenerator';

interface ExportSettingsProps {
  set: QuestionSet;
  questions: Question[];
  onBack: () => void;
}

type ExportFormat = 'pdf' | 'docx' | 'ppt' | 'csv' | 'json' | 'table';
type ColumnLayout = 'single' | 'two';
type FontFamily = 'Times New Roman' | 'Arial' | 'Noto Sans' | 'Roboto' | 'Georgia' | 'Merriweather' | 'Lora' | 'Open Sans' | 'Poppins' | 'Inter';
type HindiFontFamily = 'Noto Sans Devanagari' | 'Tiro Devanagari Hindi' | 'Baloo 2' | 'Hind' | 'Mukta';

interface ExportConfig {
  showLogo: boolean;
  organizationName: string;
  testTitle: string;
  columnLayout: ColumnLayout;
  spacingBetweenQuestions: number;
  lineSpacing: number;
  fontSize: number;
  fontFamily: FontFamily;
  hindiFontFamily: HindiFontFamily;
  language: 'English' | 'Hindi' | 'Bilingual';
  showInstructions: boolean;
  instructions: string[];
  headerBannerEnabled: boolean;
  headerBannerText: string;
  footerEnabled: boolean;
  footerText: string;
  showPageNumbers: boolean;
  watermarkEnabled: boolean;
  watermarkText: string;
  includeSolutions: boolean;
  includeAnswerKey: boolean;
  showQuestionNumbers: boolean;
  startingNumber: number;
  showMarks: boolean;
  defaultMarks: number;
  // Design
  showBorder: boolean;
  borderRadius: number;
  questionBorder: boolean;
  optionStyle: 'list' | 'grid' | 'inline';
  headerAlign: 'left' | 'center';
  accentColor: string;
  paperPadding: number;
  // Professional
  showStudentInfo: boolean;
  studentFields: string[];
  showDate: boolean;
  dateText: string;
  showDuration: boolean;
  durationText: string;
  showSubjectLine: boolean;
  subjectText: string;
  headerStyle: 'simple' | 'boxed' | 'underline' | 'double-line';
  showDifficulty: boolean;
  showSectionDivider: boolean;
  optionLabel: 'alpha' | 'roman' | 'number';
  questionSeparator: 'none' | 'line' | 'dot';
}

const GOOGLE_FONT_MAP: Record<string, string> = {
  'Noto Sans': 'Noto+Sans',
  'Roboto': 'Roboto',
  'Merriweather': 'Merriweather',
  'Lora': 'Lora',
  'Open Sans': 'Open+Sans',
  'Poppins': 'Poppins',
  'Inter': 'Inter',
  'Noto Sans Devanagari': 'Noto+Sans+Devanagari',
  'Tiro Devanagari Hindi': 'Tiro+Devanagari+Hindi',
  'Baloo 2': 'Baloo+2',
  'Hind': 'Hind',
  'Mukta': 'Mukta',
};

function stripHtml(html: string): string {
  if (!html) return '';
  return html.replace(/<[^>]*>/g, '').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').trim();
}

export const ExportSettings: React.FC<ExportSettingsProps> = ({ set, questions, onBack }) => {
  const [config, setConfig] = useState<ExportConfig>({
    showLogo: true,
    organizationName: 'Q-Bank Pro',
    testTitle: set.name,
    columnLayout: 'single',
    spacingBetweenQuestions: 1.5,
    lineSpacing: 1.5,
    fontSize: 10,
    fontFamily: 'Times New Roman',
    hindiFontFamily: 'Noto Sans Devanagari',
    language: 'English',
    showInstructions: false,
    instructions: [],
    headerBannerEnabled: false,
    headerBannerText: '',
    footerEnabled: true,
    footerText: 'Generated by Q-Bank Pro',
    showPageNumbers: true,
    watermarkEnabled: false,
    watermarkText: 'CONFIDENTIAL',
    includeSolutions: false,
    includeAnswerKey: true,
    showQuestionNumbers: true,
    startingNumber: 1,
    showMarks: false,
    defaultMarks: 1,
    showBorder: true,
    borderRadius: 0,
    questionBorder: false,
    optionStyle: 'list',
    headerAlign: 'center',
    accentColor: '#FF5A1F',
    paperPadding: 40,
    showStudentInfo: true,
    studentFields: ['Name', 'Roll No.'],
    showDate: true,
    dateText: new Date().toLocaleDateString('en-IN', { day: '2-digit', month: '2-digit', year: 'numeric' }),
    showDuration: true,
    durationText: '3 Hours',
    showSubjectLine: true,
    subjectText: set.subject || 'General',
    headerStyle: 'double-line',
    showDifficulty: false,
    showSectionDivider: true,
    optionLabel: 'alpha',
    questionSeparator: 'none',
  });

  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({
    header: true,
    layout: false,
    design: false,
    professional: false,
    instructions: false,
    banner: false,
    footer: false,
    watermark: false,
    solutions: false,
  });

  const [activeFormat, setActiveFormat] = useState<ExportFormat>('pdf');
  const [isExporting, setIsExporting] = useState(false);
  const [newInstruction, setNewInstruction] = useState('');
  const [previewScale, setPreviewScale] = useState(100);
  const [newStudentField, setNewStudentField] = useState('');

  // PPT Config
  const [pptTheme, setPptTheme] = useState<'dark' | 'light' | 'colorful'>('dark');
  const [pptShowAnswer, setPptShowAnswer] = useState(false);
  const [pptLanguage, setPptLanguage] = useState<'English' | 'Hindi'>('English');
  const [pptSlidePreview, setPptSlidePreview] = useState(0);

  // CSV/JSON Config
  const [csvIncludeHindi, setCsvIncludeHindi] = useState(true);
  const [csvIncludeSolution, setCsvIncludeSolution] = useState(false);
  const [jsonPretty, setJsonPretty] = useState(true);

  // Table Config
  const [tableShowHindi, setTableShowHindi] = useState(false);

  // Dynamic Google Font loading
  useEffect(() => {
    const fontsToLoad: string[] = [];
    const engKey = GOOGLE_FONT_MAP[config.fontFamily];
    if (engKey) fontsToLoad.push(engKey + ':wght@400;600;700');
    const hinKey = GOOGLE_FONT_MAP[config.hindiFontFamily];
    if (hinKey) fontsToLoad.push(hinKey + ':wght@400;600;700');

    if (fontsToLoad.length > 0) {
      const id = 'export-google-fonts';
      let link = document.getElementById(id) as HTMLLinkElement | null;
      const href = `https://fonts.googleapis.com/css2?${fontsToLoad.map(f => `family=${f}`).join('&')}&display=swap`;
      if (link) {
        link.href = href;
      } else {
        link = document.createElement('link');
        link.id = id;
        link.rel = 'stylesheet';
        link.href = href;
        document.head.appendChild(link);
      }
    }
  }, [config.fontFamily, config.hindiFontFamily]);

  const toggleSection = (key: string) => {
    setExpandedSections(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const updateConfig = <K extends keyof ExportConfig>(key: K, value: ExportConfig[K]) => {
    setConfig(prev => ({ ...prev, [key]: value }));
  };

  const addInstruction = () => {
    if (newInstruction.trim()) {
      updateConfig('instructions', [...config.instructions, newInstruction.trim()]);
      setNewInstruction('');
    }
  };

  const removeInstruction = (index: number) => {
    updateConfig('instructions', config.instructions.filter((_, i) => i !== index));
  };

  const totalMarks = useMemo(() => {
    if (!config.showMarks) return questions.length;
    return questions.reduce((sum, q) => sum + (q.marks || config.defaultMarks), 0);
  }, [questions, config.showMarks, config.defaultMarks]);

  // --- Export Handlers ---
  const handleExportPDF = async () => {
    setIsExporting(true);
    try {
      const pdfConfig: PDFExportConfig = {
        title: config.testTitle,
        organizationName: config.organizationName,
        language: config.language,
        columnLayout: config.columnLayout,
        fontSize: config.fontSize,
        lineSpacing: config.lineSpacing,
        spacingBetweenQuestions: config.spacingBetweenQuestions,
        headerAlign: config.headerAlign,
        headerStyle: config.headerStyle,
        accentColor: config.accentColor,
        showLogo: config.showLogo,
        showQuestionNumbers: config.showQuestionNumbers,
        showMarks: config.showMarks,
        defaultMarks: config.defaultMarks,
        showBorder: config.showBorder,
        questionBorder: config.questionBorder,
        optionStyle: config.optionStyle,
        optionLabel: config.optionLabel,
        questionSeparator: config.questionSeparator,
        showStudentInfo: config.showStudentInfo,
        studentFields: config.studentFields,
        showDate: config.showDate,
        dateText: config.dateText,
        showDuration: config.showDuration,
        durationText: config.durationText,
        showSubjectLine: config.showSubjectLine,
        subjectText: config.subjectText,
        showDifficulty: config.showDifficulty,
        showSectionDivider: config.showSectionDivider,
        showInstructions: config.showInstructions,
        instructions: config.instructions,
        headerBannerEnabled: config.headerBannerEnabled,
        headerBannerText: config.headerBannerText,
        watermarkEnabled: config.watermarkEnabled,
        watermarkText: config.watermarkText,
        footerEnabled: config.footerEnabled,
        footerText: config.footerText,
        showPageNumbers: config.showPageNumbers,
        includeAnswerKey: config.includeAnswerKey,
        includeSolutions: config.includeSolutions,
        paperPadding: config.paperPadding,
        startingNumber: config.startingNumber,
      };
      await generateQuestionSetPDF(questions, pdfConfig);
    } catch (err) {
      console.error('PDF export failed:', err);
      alert('Failed to export PDF.');
    } finally {
      setIsExporting(false);
    }
  };

  const handleExportPPT = async () => {
    setIsExporting(true);
    try {
      await generateQuestionSetPPT(questions, {
        title: config.testTitle,
        subtitle: set.description || `${questions.length} Questions`,
        theme: 'dark',
        showAnswerAfterEach: config.includeSolutions,
      });
    } catch (err) {
      console.error('PPT export failed:', err);
      alert('Failed to export PPT.');
    } finally {
      setIsExporting(false);
    }
  };

  const handleExportCSV = () => {
    const headers = ['#', 'Question (Eng)', 'Question (Hin)', 'Option A', 'Option B', 'Option C', 'Option D', 'Option E', 'Answer', 'Subject', 'Topic', 'Difficulty'];
    const rows = questions.map((q, i) => [
      i + config.startingNumber,
      `"${stripHtml(q.question_eng).replace(/"/g, '""')}"`,
      `"${stripHtml(q.question_hin).replace(/"/g, '""')}"`,
      `"${stripHtml(q.option1_eng).replace(/"/g, '""')}"`,
      `"${stripHtml(q.option2_eng).replace(/"/g, '""')}"`,
      `"${stripHtml(q.option3_eng).replace(/"/g, '""')}"`,
      `"${stripHtml(q.option4_eng).replace(/"/g, '""')}"`,
      `"${stripHtml(q.option5_eng || '').replace(/"/g, '""')}"`,
      q.answer,
      q.subject || '',
      q.topic || '',
      q.difficulty || '',
    ].join(','));

    const csv = [headers.join(','), ...rows].join('\n');
    const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${config.testTitle.replace(/\s+/g, '_')}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportJSON = () => {
    const data = {
      title: config.testTitle,
      organization: config.organizationName,
      totalQuestions: questions.length,
      totalMarks,
      exportedAt: new Date().toISOString(),
      questions: questions.map((q, i) => ({
        number: i + config.startingNumber,
        question_eng: stripHtml(q.question_eng),
        question_hin: stripHtml(q.question_hin),
        options: {
          A: stripHtml(q.option1_eng),
          B: stripHtml(q.option2_eng),
          C: stripHtml(q.option3_eng),
          D: stripHtml(q.option4_eng),
          ...(q.option5_eng ? { E: stripHtml(q.option5_eng) } : {}),
        },
        answer: q.answer,
        solution_eng: config.includeSolutions ? stripHtml(q.solution_eng) : undefined,
        subject: q.subject,
        topic: q.topic,
        difficulty: q.difficulty,
        marks: q.marks || config.defaultMarks,
      })),
    };

    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${config.testTitle.replace(/\s+/g, '_')}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportTable = () => {
    const getAnswerLabel = (q: Question) => {
      const idx = parseInt(q.answer);
      if (isNaN(idx) || idx < 1 || idx > 5) return q.answer;
      return String.fromCharCode(64 + idx);
    };

    let html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${config.testTitle}</title>
    <style>
      body { font-family: '${config.fontFamily}', serif; padding: 40px; color: #1e293b; }
      h1 { text-align: center; margin-bottom: 4px; }
      h3 { text-align: center; color: #6b7280; font-weight: normal; margin-top: 0; }
      table { width: 100%; border-collapse: collapse; margin-top: 24px; }
      th { background: #f1f5f9; padding: 10px 12px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; border: 1px solid #e2e8f0; }
      td { padding: 8px 12px; border: 1px solid #e2e8f0; font-size: ${config.fontSize}pt; vertical-align: top; }
      tr:nth-child(even) { background: #f9fafb; }
      .answer { color: #16a34a; font-weight: bold; }
      @media print { body { padding: 20px; } }
    </style></head><body>
    <h1>${config.testTitle}</h1>
    <h3>${config.organizationName} • ${questions.length} Questions • ${totalMarks} Marks</h3>
    <table>
      <thead><tr><th>#</th><th>Question</th><th>A</th><th>B</th><th>C</th><th>D</th>${questions.some(q => q.option5_eng) ? '<th>E</th>' : ''}<th>Answer</th></tr></thead>
      <tbody>`;

    questions.forEach((q, i) => {
      html += `<tr>
        <td>${i + config.startingNumber}</td>
        <td>${config.language !== 'Hindi' ? stripHtml(q.question_eng) : ''}${config.language === 'Bilingual' ? '<br><small style="color:#6b7280">' + stripHtml(q.question_hin) + '</small>' : ''}${config.language === 'Hindi' ? stripHtml(q.question_hin) : ''}</td>
        <td>${stripHtml(q.option1_eng)}</td>
        <td>${stripHtml(q.option2_eng)}</td>
        <td>${stripHtml(q.option3_eng)}</td>
        <td>${stripHtml(q.option4_eng)}</td>
        ${questions.some(qq => qq.option5_eng) ? `<td>${stripHtml(q.option5_eng || '')}</td>` : ''}
        <td class="answer">${getAnswerLabel(q)}</td>
      </tr>`;
    });

    html += `</tbody></table></body></html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const w = window.open(url, '_blank');
    if (!w) {
      const a = document.createElement('a');
      a.href = url;
      a.download = `${config.testTitle.replace(/\s+/g, '_')}_table.html`;
      a.click();
    }
    URL.revokeObjectURL(url);
  };

  const handleExportDOCX = () => {
    const _getAns = (q: Question) => { const idx = parseInt(q.answer); return (isNaN(idx) || idx < 1 || idx > 5) ? q.answer : String.fromCharCode(64 + idx); };
    const _getOL = (i: number) => config.optionLabel === 'roman' ? ['I','II','III','IV','V'][i] : config.optionLabel === 'number' ? `${i+1}` : String.fromCharCode(65+i);
    const ac = config.accentColor;
    const borderStyle = config.headerStyle === 'double-line' ? `border-bottom:3px double ${ac};` : config.headerStyle === 'underline' ? `border-bottom:1.5px solid ${ac};` : config.headerStyle === 'boxed' ? `border:2px solid ${ac};padding:12pt 16pt;` : 'border-bottom:1px solid #e5e7eb;';

    let html = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head><meta charset="utf-8"><title>${config.testTitle}</title>
    <style>
      body { font-family: '${config.fontFamily}', '${config.hindiFontFamily}', serif; font-size: ${config.fontSize}pt; line-height: ${config.lineSpacing}; color: #1e293b; padding: ${config.paperPadding}pt; }
      .header { text-align: ${config.headerAlign}; margin-bottom: 12pt; padding-bottom: 8pt; ${borderStyle} }
      .org-name { font-size: ${config.fontSize + 6}pt; font-weight: 900; color: #0f172a; }
      .test-title { font-size: ${config.fontSize + 2}pt; font-weight: 700; color: #334155; }
      .meta-row { font-size: ${config.fontSize - 2}pt; color: #64748b; margin-top: 4pt; }
      .student-info { margin-bottom: 12pt; }
      .student-field { display: inline-block; width: 45%; margin-bottom: 6pt; font-size: ${config.fontSize - 1}pt; }
      .instructions { margin-bottom: 12pt; padding: 8pt 12pt; background: #f8fafc; border: 1px solid #e2e8f0; font-size: ${config.fontSize - 1}pt; }
      .section-divider { text-align: center; font-weight: bold; text-transform: uppercase; letter-spacing: 2pt; color: ${ac}; font-size: ${config.fontSize - 2}pt; margin: 12pt 0 8pt; border-top: 1px solid ${ac}40; border-bottom: 1px solid ${ac}40; padding: 4pt 0; }
      .question { margin-bottom: ${config.spacingBetweenQuestions * 10}pt; ${config.questionBorder ? `border:1px solid #e5e7eb;padding:8pt 10pt;background:#fafafa;` : ''} }
      .q-text { font-weight: 600; margin-bottom: 4pt; }
      .q-num { font-weight: 700; color: ${ac}; }
      .q-marks { color: #94a3b8; font-weight: normal; font-size: ${config.fontSize - 2}pt; }
      .options { margin-left: ${config.optionStyle === 'list' ? '16pt' : '0'}; }
      .option { margin-bottom: 2pt; }
      .opt-label { font-weight: 600; color: ${ac}aa; }
      .answer-key { margin-top: 20pt; border-top: 2px solid ${ac}30; padding-top: 10pt; }
      .answer-key h2 { font-size: ${config.fontSize + 1}pt; color: ${ac}; }
      .answer-item { display: inline-block; width: 60pt; font-size: ${config.fontSize - 1}pt; }
      .footer { margin-top: 24pt; text-align: center; color: #9ca3af; font-size: ${config.fontSize - 3}pt; border-top: 1px solid ${ac}20; padding-top: 6pt; }
      .q-sep-line { border-top: 1px solid #e5e7eb; margin-top: 6pt; }
      .q-sep-dot { text-align: center; color: #d1d5db; letter-spacing: 6pt; font-size: 7pt; margin-top: 4pt; }
    </style></head><body>`;

    if (config.headerBannerEnabled && config.headerBannerText) {
      html += `<div style="background:${ac};color:white;padding:8pt 16pt;text-align:center;margin-bottom:12pt;font-weight:bold;">${config.headerBannerText}</div>`;
    }

    html += `<div class="header">`;
    html += `<div class="org-name">${config.organizationName}</div>`;
    html += `<div class="test-title">${config.testTitle}</div>`;
    if (config.showSubjectLine || config.showDate || config.showDuration || config.showMarks) {
      html += `<div class="meta-row">`;
      if (config.showSubjectLine) html += `<b>Subject:</b> ${config.subjectText} &nbsp;&nbsp;`;
      if (config.showDate) html += `<b>Date:</b> ${config.dateText} &nbsp;&nbsp;`;
      if (config.showDuration) html += `<b>Duration:</b> ${config.durationText} &nbsp;&nbsp;`;
      if (config.showMarks) html += `<b>Max Marks:</b> ${totalMarks}`;
      html += `</div>`;
    }
    html += `</div>`;

    if (config.showStudentInfo && config.studentFields.length > 0) {
      html += `<div class="student-info">`;
      config.studentFields.forEach(f => { html += `<div class="student-field"><b>${f}:</b> ___________________________</div>`; });
      html += `</div>`;
    }

    if (config.showInstructions && config.instructions.length > 0) {
      html += `<div class="instructions"><b>General Instructions:</b><ol>`;
      config.instructions.forEach(inst => { html += `<li>${inst}</li>`; });
      html += `</ol></div>`;
    }

    if (config.showSectionDivider) html += `<div class="section-divider">Questions</div>`;

    questions.forEach((q, i) => {
      const num = i + config.startingNumber;
      const qText = config.language !== 'Hindi' ? stripHtml(q.question_eng) : stripHtml(q.question_hin);
      const hinText = config.language === 'Bilingual' ? stripHtml(q.question_hin) : '';
      html += `<div class="question">`;
      html += `<div class="q-text">${config.showQuestionNumbers ? `<span class="q-num">Q${num}.</span> ` : ''}${qText}${config.showMarks ? ` <span class="q-marks">[${q.marks || config.defaultMarks} Mark${(q.marks || config.defaultMarks) > 1 ? 's' : ''}]</span>` : ''}</div>`;
      if (hinText) html += `<div style="color:#64748b;font-family:'${config.hindiFontFamily}',sans-serif;margin-bottom:4pt;">${hinText}</div>`;

      const optTexts = [q.option1_eng, q.option2_eng, q.option3_eng, q.option4_eng];
      if (q.option5_eng) optTexts.push(q.option5_eng);
      html += `<div class="options" ${config.optionStyle === 'grid' ? 'style="display:flex;flex-wrap:wrap;"' : ''}>`;
      optTexts.forEach((o, oi) => {
        const text = config.language !== 'Hindi' ? stripHtml(o) : stripHtml([q.option1_hin, q.option2_hin, q.option3_hin, q.option4_hin, q.option5_hin || ''][oi]);
        html += `<div class="option" ${config.optionStyle === 'grid' ? 'style="width:48%;display:inline-block;"' : ''}><span class="opt-label">(${_getOL(oi)})</span> ${text}</div>`;
      });
      html += `</div>`;

      if (config.includeSolutions) {
        const sol = config.language !== 'Hindi' ? stripHtml(q.solution_eng) : stripHtml(q.solution_hin);
        if (sol) html += `<div style="color:#2563eb;margin-top:4pt;font-size:${config.fontSize - 1}pt;"><b>Solution:</b> ${sol}</div>`;
      }
      html += `</div>`;
      if (config.questionSeparator === 'line' && i < questions.length - 1) html += `<div class="q-sep-line"></div>`;
      if (config.questionSeparator === 'dot' && i < questions.length - 1) html += `<div class="q-sep-dot">• • • • •</div>`;
    });

    if (config.includeAnswerKey) {
      html += `<div class="answer-key">`;
      if (config.showSectionDivider) html += `<div class="section-divider">Answer Key</div>`;
      else html += `<h2>Answer Key</h2>`;
      html += `<div>`;
      questions.forEach((q, i) => { html += `<span class="answer-item"><b>${i + config.startingNumber}.</b> <span style="color:${ac};font-weight:bold;">${_getAns(q)}</span></span>`; });
      html += `</div></div>`;
    }

    if (config.footerEnabled) html += `<div class="footer">${config.footerText}${config.showPageNumbers ? ' | Page 1' : ''}</div>`;
    html += `</body></html>`;

    const blob = new Blob(['\ufeff' + html], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${config.testTitle.replace(/\s+/g, '_')}.doc`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExport = async (format: ExportFormat) => {
    setIsExporting(true);
    try {
      switch (format) {
        case 'pdf': await handleExportPDF(); break;
        case 'ppt': await handleExportPPT(); break;
        case 'csv': handleExportCSV(); break;
        case 'json': handleExportJSON(); break;
        case 'table': handleExportTable(); break;
        case 'docx': handleExportDOCX(); break;
      }
    } catch (err) {
      console.error(`Export ${format} failed:`, err);
      alert(`Failed to export as ${format.toUpperCase()}.`);
    } finally {
      setIsExporting(false);
    }
  };

  // --- Compact Section ---
  const Sec = ({ id, icon: Icon, title, right, children }: { id: string; icon: any; title: string; right?: React.ReactNode; children: React.ReactNode }) => (
    <div className="border-b border-[#F0F0F0] last:border-b-0">
      <button onClick={() => toggleSection(id)} className="w-full px-3 py-2 flex items-center justify-between hover:bg-[#FAFAFA] transition-colors">
        <div className="flex items-center gap-2">
          <Icon size={13} className="text-primary" />
          <span className="text-[11px] font-bold text-slate-700">{title}</span>
        </div>
        <div className="flex items-center gap-2">
          {right}
          <ChevronDown size={12} className={`text-slate-300 transition-transform ${expandedSections[id] ? 'rotate-180' : ''}`} />
        </div>
      </button>
      {expandedSections[id] && <div className="px-3 pb-3 space-y-2">{children}</div>}
    </div>
  );

  const Tog = ({ checked, onChange }: { checked: boolean; onChange: (v: boolean) => void }) => (
    <button onClick={(e) => { e.stopPropagation(); onChange(!checked); }} className={`relative w-7 h-3.5 rounded-full transition-colors shrink-0 ${checked ? 'bg-primary' : 'bg-slate-200'}`}>
      <div className={`absolute top-[1px] w-3 h-3 rounded-full bg-white shadow transition-transform ${checked ? 'translate-x-3.5' : 'translate-x-[1px]'}`} />
    </button>
  );

  const Row = ({ label, children }: { label: string; children: React.ReactNode }) => (
    <div className="flex items-center justify-between gap-2">
      <span className="text-[10px] font-semibold text-slate-500 shrink-0">{label}</span>
      {children}
    </div>
  );

  const SmInput = ({ value, onChange, placeholder, className: cn }: { value: string; onChange: (v: string) => void; placeholder?: string; className?: string }) => (
    <input type="text" value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder}
      className={`px-2 py-1 rounded border border-[#E5E7EB] text-[10px] text-slate-700 focus:border-primary outline-none w-full ${cn || ''}`} />
  );

  const getAnswerLabel = (q: Question) => {
    const idx = parseInt(q.answer);
    if (isNaN(idx) || idx < 1 || idx > 5) return q.answer;
    return String.fromCharCode(64 + idx);
  };

  const getOptLabel = (index: number): string => {
    if (config.optionLabel === 'roman') return ['I', 'II', 'III', 'IV', 'V'][index] || '';
    if (config.optionLabel === 'number') return `${index + 1}`;
    return String.fromCharCode(65 + index);
  };

  const addStudentField = () => {
    if (newStudentField.trim() && !config.studentFields.includes(newStudentField.trim())) {
      updateConfig('studentFields', [...config.studentFields, newStudentField.trim()]);
      setNewStudentField('');
    }
  };

  const removeStudentField = (index: number) => {
    updateConfig('studentFields', config.studentFields.filter((_, i) => i !== index));
  };

  // Preview questions (show max 6 in preview)
  const previewQs = questions.slice(0, 6);

  const FORMAT_TABS = [
    { id: 'pdf' as ExportFormat, label: 'PDF', icon: FileText, color: 'text-red-500', bg: 'bg-red-50' },
    { id: 'docx' as ExportFormat, label: 'Word', icon: FileText, color: 'text-blue-500', bg: 'bg-blue-50' },
    { id: 'ppt' as ExportFormat, label: 'PPT', icon: Presentation, color: 'text-orange-500', bg: 'bg-orange-50' },
    { id: 'csv' as ExportFormat, label: 'CSV', icon: FileSpreadsheet, color: 'text-emerald-500', bg: 'bg-emerald-50' },
    { id: 'json' as ExportFormat, label: 'JSON', icon: FileJson, color: 'text-amber-500', bg: 'bg-amber-50' },
    { id: 'table' as ExportFormat, label: 'Table', icon: Table2, color: 'text-violet-500', bg: 'bg-violet-50' },
  ];

  // PPT preview data
  const pptPreviewQ = questions[pptSlidePreview] || questions[0];
  const pptBg = pptTheme === 'dark' ? '#1E293B' : pptTheme === 'colorful' ? '#FFF7ED' : '#FFFFFF';
  const pptText = pptTheme === 'dark' ? '#F1F5F9' : '#1E293B';
  const pptMuted = pptTheme === 'dark' ? '#94A3B8' : '#6B7280';
  const pptOptColors = ['#3B82F6', '#8B5CF6', '#F59E0B', '#10B981', '#EC4899'];

  // Settings panel for PDF/DOCX (shared)
  const renderDocSettings = () => (
    <div className="flex-1 overflow-y-auto">
      <Sec id="header" icon={Settings} title="Header">
        <SmInput value={config.testTitle} onChange={(v) => updateConfig('testTitle', v)} placeholder="Test Title" />
        <SmInput value={config.organizationName} onChange={(v) => updateConfig('organizationName', v)} placeholder="Organization" />
        <div className="flex gap-1">
          {(['English', 'Hindi', 'Bilingual'] as const).map(l => (
            <button key={l} onClick={() => updateConfig('language', l)}
              className={`flex-1 px-1 py-1 rounded text-[9px] font-bold transition-all ${config.language === l ? 'bg-primary text-white' : 'bg-[#F5F5F5] text-slate-400 hover:bg-slate-100'}`}>{l}</button>
          ))}
        </div>
        <Row label="Align"><div className="flex gap-1">
          {(['left', 'center'] as const).map(a => (
            <button key={a} onClick={() => updateConfig('headerAlign', a)}
              className={`px-2 py-0.5 rounded text-[9px] font-bold ${config.headerAlign === a ? 'bg-primary/10 text-primary' : 'bg-[#F5F5F5] text-slate-400'}`}>{a}</button>
          ))}
        </div></Row>
        <Row label="Logo"><Tog checked={config.showLogo} onChange={(v) => updateConfig('showLogo', v)} /></Row>
        <Row label="Numbers"><Tog checked={config.showQuestionNumbers} onChange={(v) => updateConfig('showQuestionNumbers', v)} /></Row>
        <Row label="Marks"><Tog checked={config.showMarks} onChange={(v) => updateConfig('showMarks', v)} /></Row>
        {config.showMarks && <Row label="Default"><input type="number" min={1} max={10} value={config.defaultMarks}
          onChange={(e) => updateConfig('defaultMarks', parseInt(e.target.value) || 1)}
          className="w-14 px-1.5 py-0.5 rounded border border-[#E5E7EB] text-[10px] text-slate-700 outline-none" /></Row>}
      </Sec>
      <Sec id="layout" icon={Columns} title="Layout">
        <div className="flex gap-1.5">
          <button onClick={() => updateConfig('columnLayout', 'single')}
            className={`flex-1 p-1.5 rounded border-2 flex flex-col items-center gap-1 transition-all ${config.columnLayout === 'single' ? 'border-primary bg-primary/5' : 'border-[#E5E7EB]'}`}>
            <div className="w-6 h-8 border border-current rounded-[1px] p-0.5"><div className="w-full h-full bg-current opacity-20" /></div>
            <span className="text-[8px] font-bold">1 COL</span>
          </button>
          <button onClick={() => updateConfig('columnLayout', 'two')}
            className={`flex-1 p-1.5 rounded border-2 flex flex-col items-center gap-1 transition-all ${config.columnLayout === 'two' ? 'border-primary bg-primary/5' : 'border-[#E5E7EB]'}`}>
            <div className="w-6 h-8 border border-current rounded-[1px] p-0.5 flex gap-px"><div className="flex-1 bg-current opacity-20" /><div className="flex-1 bg-current opacity-20" /></div>
            <span className="text-[8px] font-bold">2 COL</span>
          </button>
        </div>
        <Row label={`Q Spacing (${config.spacingBetweenQuestions}x)`}><input type="range" min={0.5} max={3} step={0.1} value={config.spacingBetweenQuestions} onChange={(e) => updateConfig('spacingBetweenQuestions', parseFloat(e.target.value))} className="w-28 accent-primary h-1" /></Row>
        <Row label={`Line Spacing (${config.lineSpacing}x)`}><input type="range" min={1} max={3} step={0.1} value={config.lineSpacing} onChange={(e) => updateConfig('lineSpacing', parseFloat(e.target.value))} className="w-28 accent-primary h-1" /></Row>
        <Row label={`Font Size (${config.fontSize}pt)`}><input type="range" min={8} max={16} step={0.5} value={config.fontSize} onChange={(e) => updateConfig('fontSize', parseFloat(e.target.value))} className="w-28 accent-primary h-1" /></Row>
        <Row label={`Padding (${config.paperPadding}px)`}><input type="range" min={10} max={80} step={5} value={config.paperPadding} onChange={(e) => updateConfig('paperPadding', parseInt(e.target.value))} className="w-28 accent-primary h-1" /></Row>
        <Row label="Eng Font">
          <select value={config.fontFamily} onChange={(e) => updateConfig('fontFamily', e.target.value as FontFamily)}
            className="px-1.5 py-0.5 rounded border border-[#E5E7EB] text-[10px] text-slate-700 outline-none bg-white w-32" style={{ fontFamily: `'${config.fontFamily}', serif` }}>
            <option value="Times New Roman">Times New Roman</option><option value="Arial">Arial</option>
            <option value="Georgia">Georgia</option><option value="Noto Sans">Noto Sans</option>
            <option value="Roboto">Roboto</option><option value="Merriweather">Merriweather</option>
            <option value="Lora">Lora</option><option value="Open Sans">Open Sans</option>
            <option value="Poppins">Poppins</option><option value="Inter">Inter</option>
          </select>
        </Row>
        <Row label="Hindi Font">
          <select value={config.hindiFontFamily} onChange={(e) => updateConfig('hindiFontFamily', e.target.value as HindiFontFamily)}
            className="px-1.5 py-0.5 rounded border border-[#E5E7EB] text-[10px] text-slate-700 outline-none bg-white w-32" style={{ fontFamily: `'${config.hindiFontFamily}', sans-serif` }}>
            <option value="Noto Sans Devanagari">Noto Sans Devanagari</option><option value="Tiro Devanagari Hindi">Tiro Devanagari Hindi</option>
            <option value="Baloo 2">Baloo 2</option><option value="Hind">Hind</option><option value="Mukta">Mukta</option>
          </select>
        </Row>
      </Sec>
      <Sec id="design" icon={Palette} title="Design">
        <Row label="Paper Border"><Tog checked={config.showBorder} onChange={(v) => updateConfig('showBorder', v)} /></Row>
        {config.showBorder && <Row label={`Border Radius (${config.borderRadius}px)`}><input type="range" min={0} max={16} step={1} value={config.borderRadius} onChange={(e) => updateConfig('borderRadius', parseInt(e.target.value))} className="w-28 accent-primary h-1" /></Row>}
        <Row label="Q Border"><Tog checked={config.questionBorder} onChange={(v) => updateConfig('questionBorder', v)} /></Row>
        <Row label="Options Style"><div className="flex gap-1">
          {(['list', 'grid', 'inline'] as const).map(s => (
            <button key={s} onClick={() => updateConfig('optionStyle', s)} className={`px-2 py-0.5 rounded text-[9px] font-bold capitalize ${config.optionStyle === s ? 'bg-primary/10 text-primary' : 'bg-[#F5F5F5] text-slate-400'}`}>{s}</button>
          ))}
        </div></Row>
        <Row label="Accent"><div className="flex gap-1.5 items-center">
          {['#FF5A1F', '#2563EB', '#16A34A', '#7C3AED', '#DC2626', '#0891B2', '#000000'].map(c => (
            <button key={c} onClick={() => updateConfig('accentColor', c)} className={`w-4 h-4 rounded-full border-2 transition-all ${config.accentColor === c ? 'border-slate-900 scale-125' : 'border-transparent'}`} style={{ backgroundColor: c }} />
          ))}
        </div></Row>
        <Row label="Opt Label"><div className="flex gap-1">
          {(['alpha', 'roman', 'number'] as const).map(s => (
            <button key={s} onClick={() => updateConfig('optionLabel', s)} className={`px-2 py-0.5 rounded text-[9px] font-bold ${config.optionLabel === s ? 'bg-primary/10 text-primary' : 'bg-[#F5F5F5] text-slate-400'}`}>
              {s === 'alpha' ? 'A B C' : s === 'roman' ? 'I II III' : '1 2 3'}
            </button>
          ))}
        </div></Row>
        <Row label="Q Separator"><div className="flex gap-1">
          {(['none', 'line', 'dot'] as const).map(s => (
            <button key={s} onClick={() => updateConfig('questionSeparator', s)} className={`px-2 py-0.5 rounded text-[9px] font-bold capitalize ${config.questionSeparator === s ? 'bg-primary/10 text-primary' : 'bg-[#F5F5F5] text-slate-400'}`}>{s}</button>
          ))}
        </div></Row>
      </Sec>
      <Sec id="professional" icon={GraduationCap} title="Professional">
        <Row label="Header Style"><div className="flex gap-1">
          {(['simple', 'boxed', 'underline', 'double-line'] as const).map(s => (
            <button key={s} onClick={() => updateConfig('headerStyle', s)} className={`px-1.5 py-0.5 rounded text-[8px] font-bold capitalize ${config.headerStyle === s ? 'bg-primary/10 text-primary' : 'bg-[#F5F5F5] text-slate-400'}`}>
              {s === 'double-line' ? '═══' : s === 'underline' ? '───' : s === 'boxed' ? '[ ]' : '—'}
            </button>
          ))}
        </div></Row>
        <Row label="Student Info"><Tog checked={config.showStudentInfo} onChange={(v) => updateConfig('showStudentInfo', v)} /></Row>
        {config.showStudentInfo && <>
          <div className="flex flex-wrap gap-1">
            {config.studentFields.map((f, i) => (
              <span key={i} className="inline-flex items-center gap-1 bg-[#F5F5F5] rounded px-1.5 py-0.5 text-[9px] text-slate-600">
                {f} <button onClick={() => removeStudentField(i)} className="text-slate-300 hover:text-red-500"><Trash2 size={8} /></button>
              </span>
            ))}
          </div>
          <div className="flex gap-1">
            <input type="text" value={newStudentField} onChange={(e) => setNewStudentField(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && addStudentField()} placeholder="Add field..." className="flex-1 px-2 py-0.5 rounded border border-[#E5E7EB] text-[9px] outline-none" />
            <button onClick={addStudentField} className="px-1.5 py-0.5 rounded bg-primary/10 text-primary text-[9px] font-bold"><Plus size={8} /></button>
          </div>
        </>}
        <Row label="Date"><Tog checked={config.showDate} onChange={(v) => updateConfig('showDate', v)} /></Row>
        {config.showDate && <SmInput value={config.dateText} onChange={(v) => updateConfig('dateText', v)} placeholder="Date..." />}
        <Row label="Duration"><Tog checked={config.showDuration} onChange={(v) => updateConfig('showDuration', v)} /></Row>
        {config.showDuration && <SmInput value={config.durationText} onChange={(v) => updateConfig('durationText', v)} placeholder="3 Hours" />}
        <Row label="Subject Line"><Tog checked={config.showSubjectLine} onChange={(v) => updateConfig('showSubjectLine', v)} /></Row>
        {config.showSubjectLine && <SmInput value={config.subjectText} onChange={(v) => updateConfig('subjectText', v)} placeholder="Subject" />}
        <Row label="Difficulty"><Tog checked={config.showDifficulty} onChange={(v) => updateConfig('showDifficulty', v)} /></Row>
        <Row label="Section Divider"><Tog checked={config.showSectionDivider} onChange={(v) => updateConfig('showSectionDivider', v)} /></Row>
      </Sec>
      <Sec id="instructions" icon={BookOpen} title="Instructions" right={<Tog checked={config.showInstructions} onChange={(v) => updateConfig('showInstructions', v)} />}>
        {config.instructions.map((inst, i) => (
          <div key={i} className="flex items-center gap-1.5 bg-[#FAFAFA] rounded p-1.5 text-[10px] text-slate-600">
            <span className="font-bold text-slate-400">{i + 1}.</span><span className="flex-1 truncate">{inst}</span>
            <button onClick={() => removeInstruction(i)} className="text-slate-300 hover:text-red-500"><Trash2 size={10} /></button>
          </div>
        ))}
        <div className="flex gap-1">
          <input type="text" value={newInstruction} onChange={(e) => setNewInstruction(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && addInstruction()} placeholder="Add..." className="flex-1 px-2 py-1 rounded border border-[#E5E7EB] text-[10px] outline-none" />
          <button onClick={addInstruction} className="px-2 py-1 rounded bg-primary/10 text-primary text-[9px] font-bold"><Plus size={10} /></button>
        </div>
      </Sec>
      <Sec id="banner" icon={ImageIcon} title="Banner" right={<Tog checked={config.headerBannerEnabled} onChange={(v) => updateConfig('headerBannerEnabled', v)} />}>
        {config.headerBannerEnabled && <SmInput value={config.headerBannerText} onChange={(v) => updateConfig('headerBannerText', v)} placeholder="Banner text..." />}
      </Sec>
      <Sec id="footer" icon={AlignLeft} title="Footer" right={<Tog checked={config.footerEnabled} onChange={(v) => updateConfig('footerEnabled', v)} />}>
        {config.footerEnabled && <><SmInput value={config.footerText} onChange={(v) => updateConfig('footerText', v)} placeholder="Footer text..." /><Row label="Page Numbers"><Tog checked={config.showPageNumbers} onChange={(v) => updateConfig('showPageNumbers', v)} /></Row></>}
      </Sec>
      <Sec id="watermark" icon={Shield} title="Watermark" right={<Tog checked={config.watermarkEnabled} onChange={(v) => updateConfig('watermarkEnabled', v)} />}>
        {config.watermarkEnabled && <SmInput value={config.watermarkText} onChange={(v) => updateConfig('watermarkText', v)} placeholder="CONFIDENTIAL" />}
      </Sec>
      <Sec id="solutions" icon={CheckCircle} title="Solutions & Answers">
        <Row label="Include Solutions"><Tog checked={config.includeSolutions} onChange={(v) => updateConfig('includeSolutions', v)} /></Row>
        <Row label="Answer Key"><Tog checked={config.includeAnswerKey} onChange={(v) => updateConfig('includeAnswerKey', v)} /></Row>
      </Sec>
    </div>
  );

  // PPT Settings panel
  const renderPptSettings = () => (
    <div className="flex-1 overflow-y-auto">
      <Sec id="header" icon={Settings} title="Presentation">
        <SmInput value={config.testTitle} onChange={(v) => updateConfig('testTitle', v)} placeholder="Presentation Title" />
        <SmInput value={config.organizationName} onChange={(v) => updateConfig('organizationName', v)} placeholder="Subtitle" />
      </Sec>
      <Sec id="design" icon={Paintbrush} title="Theme">
        <div className="grid grid-cols-3 gap-1.5">
          {([
            { id: 'dark' as const, label: 'Dark', icon: Moon, bg: '#1E293B', fg: '#F1F5F9' },
            { id: 'light' as const, label: 'Light', icon: Sun, bg: '#FFFFFF', fg: '#1E293B' },
            { id: 'colorful' as const, label: 'Colorful', icon: Palette, bg: '#FFF7ED', fg: '#EA580C' },
          ]).map(t => (
            <button key={t.id} onClick={() => setPptTheme(t.id)}
              className={`p-2 rounded-lg border-2 flex flex-col items-center gap-1 transition-all ${pptTheme === t.id ? 'border-primary' : 'border-[#E5E7EB]'}`}>
              <div className="w-full h-6 rounded" style={{ backgroundColor: t.bg, border: '1px solid #e5e7eb' }}>
                <div className="w-3/4 h-1 rounded mt-1.5 mx-auto" style={{ backgroundColor: t.fg, opacity: 0.5 }} />
              </div>
              <span className="text-[8px] font-bold text-slate-600">{t.label}</span>
            </button>
          ))}
        </div>
      </Sec>
      <Sec id="layout" icon={Columns} title="Slide Options">
        <Row label="Language"><div className="flex gap-1">
          {(['English', 'Hindi'] as const).map(l => (
            <button key={l} onClick={() => setPptLanguage(l)} className={`px-2 py-0.5 rounded text-[9px] font-bold ${pptLanguage === l ? 'bg-primary/10 text-primary' : 'bg-[#F5F5F5] text-slate-400'}`}>{l}</button>
          ))}
        </div></Row>
        <Row label="Show Answer After Each"><Tog checked={pptShowAnswer} onChange={setPptShowAnswer} /></Row>
        <Row label="Include Solutions"><Tog checked={config.includeSolutions} onChange={(v) => updateConfig('includeSolutions', v)} /></Row>
      </Sec>
      <Sec id="professional" icon={Eye} title="Slide Navigation">
        <Row label={`Slide ${pptSlidePreview + 1} of ${questions.length}`}>
          <div className="flex gap-1">
            <button onClick={() => setPptSlidePreview(Math.max(0, pptSlidePreview - 1))} className="px-2 py-0.5 rounded bg-[#F5F5F5] text-[9px] font-bold text-slate-500 hover:bg-slate-200 disabled:opacity-30" disabled={pptSlidePreview === 0}>Prev</button>
            <button onClick={() => setPptSlidePreview(Math.min(questions.length - 1, pptSlidePreview + 1))} className="px-2 py-0.5 rounded bg-[#F5F5F5] text-[9px] font-bold text-slate-500 hover:bg-slate-200 disabled:opacity-30" disabled={pptSlidePreview >= questions.length - 1}>Next</button>
          </div>
        </Row>
        <div className="grid grid-cols-6 gap-1 mt-1">
          {questions.slice(0, 18).map((_, i) => (
            <button key={i} onClick={() => setPptSlidePreview(i)}
              className={`py-1 rounded text-[8px] font-bold transition-all ${pptSlidePreview === i ? 'bg-primary text-white' : 'bg-[#F5F5F5] text-slate-400 hover:bg-slate-200'}`}>{i + 1}</button>
          ))}
          {questions.length > 18 && <span className="text-[8px] text-slate-300 col-span-6 text-center">+{questions.length - 18} more</span>}
        </div>
      </Sec>
    </div>
  );

  // CSV Settings
  const renderCsvSettings = () => (
    <div className="flex-1 overflow-y-auto">
      <Sec id="header" icon={Settings} title="CSV Options">
        <SmInput value={config.testTitle} onChange={(v) => updateConfig('testTitle', v)} placeholder="File Name" />
        <Row label="Include Hindi"><Tog checked={csvIncludeHindi} onChange={setCsvIncludeHindi} /></Row>
        <Row label="Include Solutions"><Tog checked={csvIncludeSolution} onChange={setCsvIncludeSolution} /></Row>
        <Row label={`Starting # (${config.startingNumber})`}><input type="number" min={1} max={100} value={config.startingNumber} onChange={(e) => updateConfig('startingNumber', parseInt(e.target.value) || 1)} className="w-14 px-1.5 py-0.5 rounded border border-[#E5E7EB] text-[10px] text-slate-700 outline-none" /></Row>
      </Sec>
      <Sec id="layout" icon={Eye} title="Preview Info">
        <div className="text-[10px] text-slate-500 space-y-1">
          <div className="flex justify-between"><span>Total Rows</span><span className="font-bold text-slate-700">{questions.length}</span></div>
          <div className="flex justify-between"><span>Columns</span><span className="font-bold text-slate-700">{csvIncludeHindi ? 12 : 10}{csvIncludeSolution ? ' + Solution' : ''}</span></div>
          <div className="flex justify-between"><span>Format</span><span className="font-bold text-slate-700">UTF-8 CSV</span></div>
        </div>
      </Sec>
    </div>
  );

  // JSON Settings
  const renderJsonSettings = () => (
    <div className="flex-1 overflow-y-auto">
      <Sec id="header" icon={Settings} title="JSON Options">
        <SmInput value={config.testTitle} onChange={(v) => updateConfig('testTitle', v)} placeholder="File Name" />
        <Row label="Pretty Print"><Tog checked={jsonPretty} onChange={setJsonPretty} /></Row>
        <Row label="Include Solutions"><Tog checked={config.includeSolutions} onChange={(v) => updateConfig('includeSolutions', v)} /></Row>
      </Sec>
      <Sec id="layout" icon={Eye} title="Structure Info">
        <div className="text-[10px] text-slate-500 space-y-1">
          <div className="flex justify-between"><span>Questions</span><span className="font-bold text-slate-700">{questions.length}</span></div>
          <div className="flex justify-between"><span>Fields per Q</span><span className="font-bold text-slate-700">question, options, answer, meta</span></div>
          <div className="flex justify-between"><span>Encoding</span><span className="font-bold text-slate-700">UTF-8 JSON</span></div>
        </div>
      </Sec>
    </div>
  );

  // Table Settings
  const renderTableSettings = () => (
    <div className="flex-1 overflow-y-auto">
      <Sec id="header" icon={Settings} title="Table Options">
        <SmInput value={config.testTitle} onChange={(v) => updateConfig('testTitle', v)} placeholder="Title" />
        <Row label="Show Hindi"><Tog checked={tableShowHindi} onChange={setTableShowHindi} /></Row>
        <Row label="Font Size"><input type="range" min={8} max={16} step={0.5} value={config.fontSize} onChange={(e) => updateConfig('fontSize', parseFloat(e.target.value))} className="w-28 accent-primary h-1" /></Row>
      </Sec>
    </div>
  );

  // PDF/DOCX Preview
  const renderDocPreview = () => (
    <div className="flex-1 overflow-auto p-6 flex justify-center" style={{ background: '#E8EAED' }}>
      <div className="w-full max-w-[750px]" style={{ transform: `scale(${previewScale / 100})`, transformOrigin: 'top center' }}>
        <div className="bg-white mx-auto relative" style={{
          padding: `${config.paperPadding}px`, border: config.showBorder ? '1.5px solid #d1d5db' : 'none',
          borderRadius: `${config.borderRadius}px`, fontFamily: `'${config.fontFamily}', '${config.hindiFontFamily}', serif`,
          fontSize: `${config.fontSize}pt`, lineHeight: config.lineSpacing, minHeight: '900px',
          boxShadow: '0 4px 24px rgba(0,0,0,0.12), 0 1px 4px rgba(0,0,0,0.06)',
        }}>
          {config.watermarkEnabled && (
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none overflow-hidden" style={{ borderRadius: `${config.borderRadius}px` }}>
              <span className="font-black select-none whitespace-nowrap" style={{ fontSize: '64px', color: 'rgba(0,0,0,0.04)', transform: 'rotate(-35deg)' }}>{config.watermarkText}</span>
            </div>
          )}
          {config.headerBannerEnabled && config.headerBannerText && (
            <div className="mb-4 py-2 px-4 text-center font-bold text-white" style={{ fontSize: `${Math.max(config.fontSize - 1, 8)}pt`, backgroundColor: config.accentColor, borderRadius: `${Math.min(config.borderRadius, 6)}px` }}>{config.headerBannerText}</div>
          )}
          <div className={`${config.headerAlign === 'center' ? 'text-center' : 'text-left'}`} style={{ ...(config.headerStyle === 'boxed' ? { border: `2px solid ${config.accentColor}`, padding: '12px 16px', borderRadius: `${Math.min(config.borderRadius, 8)}px`, marginBottom: '16px' } : { marginBottom: '12px' }) }}>
            {config.showLogo && (
              <div className={`inline-flex items-center justify-center rounded-md mb-2 ${config.headerAlign === 'center' ? '' : 'float-left mr-3'}`} style={{ width: '36px', height: '36px', backgroundColor: config.accentColor + '12', color: config.accentColor }}><GraduationCap size={18} /></div>
            )}
            <div className="font-black text-slate-900" style={{ fontSize: `${config.fontSize + 6}pt`, fontFamily: `'${config.fontFamily}', serif` }}>{config.organizationName}</div>
            <div className="font-bold text-slate-700 mt-0.5" style={{ fontSize: `${config.fontSize + 2}pt` }}>{config.testTitle}</div>
            {(config.showSubjectLine || config.showDate || config.showDuration) && (
              <div className="flex items-center justify-center gap-4 mt-1.5 flex-wrap" style={{ fontSize: `${Math.max(config.fontSize - 2, 7)}pt`, justifyContent: config.headerAlign === 'left' ? 'flex-start' : 'center' }}>
                {config.showSubjectLine && <span className="text-slate-500"><strong>Subject:</strong> {config.subjectText}</span>}
                {config.showDate && <span className="text-slate-500"><strong>Date:</strong> {config.dateText}</span>}
                {config.showDuration && <span className="text-slate-500"><strong>Duration:</strong> {config.durationText}</span>}
                {config.showMarks && <span className="text-slate-500"><strong>Max Marks:</strong> {totalMarks}</span>}
              </div>
            )}
            {config.headerStyle === 'double-line' && <div className="mt-3" style={{ borderTop: `3px double ${config.accentColor}` }} />}
            {config.headerStyle === 'underline' && <div className="mt-3" style={{ borderTop: `1.5px solid ${config.accentColor}` }} />}
            {config.headerStyle === 'simple' && <div className="mt-3" style={{ borderTop: '1px solid #e5e7eb' }} />}
            {config.showLogo && config.headerAlign === 'left' && <div style={{ clear: 'both' }} />}
          </div>
          {config.showStudentInfo && config.studentFields.length > 0 && (
            <div className="mb-4 grid gap-2" style={{ gridTemplateColumns: `repeat(${Math.min(config.studentFields.length, 3)}, 1fr)`, fontSize: `${Math.max(config.fontSize - 1, 8)}pt` }}>
              {config.studentFields.map((field, i) => (
                <div key={i} className="flex items-center gap-1"><span className="font-semibold text-slate-600 whitespace-nowrap">{field}:</span><span className="flex-1 border-b border-dotted border-slate-300 min-w-[60px]">&nbsp;</span></div>
              ))}
            </div>
          )}
          {config.showInstructions && config.instructions.length > 0 && (
            <div className="mb-4 p-3 border" style={{ borderColor: config.accentColor + '30', borderRadius: `${Math.min(config.borderRadius, 8)}px`, backgroundColor: config.accentColor + '05' }}>
              <div className="font-bold text-slate-700 mb-1" style={{ fontSize: `${Math.max(config.fontSize - 1, 8)}pt` }}>General Instructions:</div>
              <ol className="text-slate-500 list-decimal list-inside space-y-0.5" style={{ fontSize: `${Math.max(config.fontSize - 2, 7)}pt` }}>{config.instructions.map((inst, i) => <li key={i}>{inst}</li>)}</ol>
            </div>
          )}
          {config.showSectionDivider && (
            <div className="flex items-center gap-2 mb-3"><div className="flex-1 border-t" style={{ borderColor: config.accentColor + '40' }} /><span className="font-bold uppercase tracking-wider" style={{ fontSize: `${Math.max(config.fontSize - 2, 7)}pt`, color: config.accentColor }}>Questions</span><div className="flex-1 border-t" style={{ borderColor: config.accentColor + '40' }} /></div>
          )}
          <div className={config.columnLayout === 'two' ? 'columns-2 gap-6' : ''}>
            {previewQs.map((q, i) => {
              const num = i + config.startingNumber;
              const qText = config.language !== 'Hindi' ? stripHtml(q.question_eng) : stripHtml(q.question_hin);
              const hinText = config.language === 'Bilingual' ? stripHtml(q.question_hin) : '';
              const hinFont = config.language !== 'English' ? config.hindiFontFamily : config.fontFamily;
              const optTexts = [
                config.language !== 'Hindi' ? stripHtml(q.option1_eng) : stripHtml(q.option1_hin),
                config.language !== 'Hindi' ? stripHtml(q.option2_eng) : stripHtml(q.option2_hin),
                config.language !== 'Hindi' ? stripHtml(q.option3_eng) : stripHtml(q.option3_hin),
                config.language !== 'Hindi' ? stripHtml(q.option4_eng) : stripHtml(q.option4_hin),
              ];
              if (q.option5_eng) optTexts.push(config.language !== 'Hindi' ? stripHtml(q.option5_eng) : stripHtml(q.option5_hin || ''));
              return (
                <div key={q.id} className="break-inside-avoid" style={{ marginBottom: `${config.spacingBetweenQuestions * 10}px`, padding: config.questionBorder ? '8px 10px' : '0', border: config.questionBorder ? '1px solid #e5e7eb' : 'none', borderRadius: config.questionBorder ? `${Math.min(config.borderRadius, 8)}px` : '0', backgroundColor: config.questionBorder ? '#fafafa' : 'transparent' }}>
                  <div className="font-semibold text-slate-800" style={{ fontSize: `${config.fontSize}pt`, fontFamily: `'${config.fontFamily}', serif` }}>
                    {config.showQuestionNumbers && <span className="font-bold" style={{ color: config.accentColor }}>Q{num}. </span>}
                    {qText}
                    {config.showMarks && <span className="text-slate-400 font-normal ml-1" style={{ fontSize: `${Math.max(config.fontSize - 2, 7)}pt` }}>[{q.marks || config.defaultMarks} Mark{(q.marks || config.defaultMarks) > 1 ? 's' : ''}]</span>}
                    {config.showDifficulty && q.difficulty && (
                      <span className="ml-1.5 px-1.5 py-0.5 rounded-sm font-bold text-white inline-block" style={{ fontSize: `${Math.max(config.fontSize - 3, 6)}pt`, backgroundColor: q.difficulty === 'Easy' ? '#16a34a' : q.difficulty === 'Medium' ? '#f59e0b' : '#dc2626' }}>{q.difficulty}</span>
                    )}
                  </div>
                  {hinText && <div className="text-slate-400 mt-0.5" style={{ fontSize: `${Math.max(config.fontSize - 1, 8)}pt`, fontFamily: `'${hinFont}', sans-serif` }}>{hinText}</div>}
                  <div className={`mt-1.5 ${config.optionStyle === 'grid' ? 'grid grid-cols-2 gap-x-4 gap-y-1' : config.optionStyle === 'inline' ? 'flex flex-wrap gap-x-5 gap-y-1' : 'space-y-1'}`} style={{ marginLeft: config.optionStyle === 'list' ? '12px' : '0' }}>
                    {optTexts.map((text, oi) => (
                      <div key={oi} className="text-slate-600" style={{ fontSize: `${config.fontSize}pt` }}><span className="font-semibold" style={{ color: config.accentColor + 'aa' }}>({getOptLabel(oi)})</span> {text}</div>
                    ))}
                  </div>
                  {config.questionSeparator === 'line' && i < previewQs.length - 1 && <div className="mt-2" style={{ borderTop: '1px solid #e5e7eb' }} />}
                  {config.questionSeparator === 'dot' && i < previewQs.length - 1 && <div className="mt-2 text-center text-slate-200 tracking-[8px]" style={{ fontSize: '8px' }}>• • • • •</div>}
                </div>
              );
            })}
          </div>
          {questions.length > 6 && <div className="text-center py-3 text-slate-300 font-medium" style={{ fontSize: `${Math.max(config.fontSize - 2, 7)}pt`, borderTop: '1px dashed #e5e7eb' }}>and {questions.length - 6} more questions</div>}
          {config.includeAnswerKey && (
            <div className="mt-5 pt-3" style={{ borderTop: `2px solid ${config.accentColor}30` }}>
              {config.showSectionDivider ? (
                <div className="flex items-center gap-2 mb-2"><div className="flex-1 border-t" style={{ borderColor: config.accentColor + '40' }} /><span className="font-bold uppercase tracking-wider" style={{ fontSize: `${Math.max(config.fontSize - 2, 7)}pt`, color: config.accentColor }}>Answer Key</span><div className="flex-1 border-t" style={{ borderColor: config.accentColor + '40' }} /></div>
              ) : <div className="font-bold text-slate-700 mb-2" style={{ fontSize: `${config.fontSize}pt` }}>Answer Key</div>}
              <div className="flex flex-wrap gap-x-3 gap-y-1" style={{ fontSize: `${Math.max(config.fontSize - 1, 8)}pt` }}>
                {previewQs.map((q, i) => (<span key={q.id} className="text-slate-500"><span className="font-bold">{i + config.startingNumber}.</span> <span style={{ color: config.accentColor }} className="font-bold">{getAnswerLabel(q)}</span></span>))}
                {questions.length > 6 && <span className="text-slate-300">...</span>}
              </div>
            </div>
          )}
          {config.footerEnabled && (
            <div className="mt-8 pt-2 flex items-center justify-between" style={{ borderTop: `1px solid ${config.accentColor}20`, fontSize: `${Math.max(config.fontSize - 3, 6)}pt` }}>
              <span className="text-slate-400">{config.footerText}</span>
              {config.showPageNumbers && <span className="text-slate-400">Page 1 of 1</span>}
            </div>
          )}
        </div>
      </div>
    </div>
  );

  // PPT Preview
  const renderPptPreview = () => {
    if (!pptPreviewQ) return null;
    const qText = pptLanguage === 'Hindi' ? stripHtml(pptPreviewQ.question_hin) : stripHtml(pptPreviewQ.question_eng);
    const opts = [
      pptLanguage === 'Hindi' ? stripHtml(pptPreviewQ.option1_hin) : stripHtml(pptPreviewQ.option1_eng),
      pptLanguage === 'Hindi' ? stripHtml(pptPreviewQ.option2_hin) : stripHtml(pptPreviewQ.option2_eng),
      pptLanguage === 'Hindi' ? stripHtml(pptPreviewQ.option3_hin) : stripHtml(pptPreviewQ.option3_eng),
      pptLanguage === 'Hindi' ? stripHtml(pptPreviewQ.option4_hin) : stripHtml(pptPreviewQ.option4_eng),
    ];
    return (
      <div className="flex-1 overflow-auto p-6 flex flex-col items-center justify-center" style={{ background: '#E8EAED' }}>
        <div style={{ transform: `scale(${previewScale / 100})`, transformOrigin: 'center center' }}>
          {/* Slide */}
          <div className="rounded-lg overflow-hidden" style={{ width: '720px', height: '405px', backgroundColor: pptBg, boxShadow: '0 8px 32px rgba(0,0,0,0.2), 0 2px 8px rgba(0,0,0,0.1)', position: 'relative' }}>
            {/* Q number badge */}
            <div className="absolute top-4 left-5 px-3 py-1 rounded-md text-white font-bold text-sm" style={{ backgroundColor: '#FF5A1F' }}>Q{pptSlidePreview + 1}</div>
            {/* Question text */}
            <div className="absolute top-16 left-5 right-5 font-medium" style={{ color: pptText, fontSize: '16px', lineHeight: 1.5 }}>{qText}</div>
            {/* Options 2x2 grid */}
            <div className="absolute bottom-8 left-5 right-5 grid grid-cols-2 gap-3">
              {opts.map((opt, oi) => (
                <div key={oi} className="rounded-lg px-3 py-2.5 flex items-start gap-2" style={{ backgroundColor: pptTheme === 'dark' ? '#334155' : '#F9FAFB', border: `1px solid ${pptTheme === 'dark' ? '#475569' : '#E5E7EB'}` }}>
                  <span className="font-bold text-sm shrink-0" style={{ color: pptOptColors[oi] }}>{String.fromCharCode(65 + oi)})</span>
                  <span className="text-sm" style={{ color: pptText }}>{opt}</span>
                </div>
              ))}
            </div>
            {/* Footer */}
            <div className="absolute bottom-2 right-5 text-xs" style={{ color: pptMuted }}>{pptSlidePreview + 1} / {questions.length}</div>
          </div>
        </div>
        {/* Slide thumbnails */}
        <div className="flex gap-2 mt-4 overflow-x-auto max-w-[720px] pb-2">
          {questions.slice(0, 12).map((_, i) => (
            <button key={i} onClick={() => setPptSlidePreview(i)}
              className={`shrink-0 w-16 h-9 rounded border-2 flex items-center justify-center text-[8px] font-bold transition-all ${pptSlidePreview === i ? 'border-primary bg-primary/10 text-primary' : 'border-[#E5E7EB] bg-white text-slate-400 hover:border-slate-300'}`}
              style={{ backgroundColor: pptSlidePreview === i ? undefined : pptBg }}>
              Q{i + 1}
            </button>
          ))}
          {questions.length > 12 && <span className="text-[9px] text-slate-400 self-center shrink-0">+{questions.length - 12}</span>}
        </div>
      </div>
    );
  };

  // CSV Preview
  const renderCsvPreview = () => (
    <div className="flex-1 overflow-auto p-6" style={{ background: '#E8EAED' }}>
      <div className="bg-white rounded-lg shadow-lg overflow-hidden border border-[#E5E7EB]">
        <div className="overflow-x-auto">
          <table className="w-full text-[10px]">
            <thead><tr className="bg-slate-50">
              {['#', 'Question', csvIncludeHindi && 'Hindi', 'A', 'B', 'C', 'D', 'Answer', 'Subject', 'Difficulty'].filter(Boolean).map((h, i) => (
                <th key={i} className="px-3 py-2 text-left font-bold text-slate-500 border-b border-[#E5E7EB] whitespace-nowrap">{h}</th>
              ))}
            </tr></thead>
            <tbody>
              {questions.slice(0, 8).map((q, i) => (
                <tr key={q.id} className={i % 2 === 0 ? 'bg-white' : 'bg-slate-50/50'}>
                  <td className="px-3 py-2 border-b border-[#F0F0F0] font-bold text-slate-400">{i + config.startingNumber}</td>
                  <td className="px-3 py-2 border-b border-[#F0F0F0] text-slate-700 max-w-[200px] truncate">{stripHtml(q.question_eng).substring(0, 60)}...</td>
                  {csvIncludeHindi && <td className="px-3 py-2 border-b border-[#F0F0F0] text-slate-400 max-w-[150px] truncate">{stripHtml(q.question_hin).substring(0, 40)}...</td>}
                  <td className="px-3 py-2 border-b border-[#F0F0F0] text-slate-600">{stripHtml(q.option1_eng).substring(0, 25)}</td>
                  <td className="px-3 py-2 border-b border-[#F0F0F0] text-slate-600">{stripHtml(q.option2_eng).substring(0, 25)}</td>
                  <td className="px-3 py-2 border-b border-[#F0F0F0] text-slate-600">{stripHtml(q.option3_eng).substring(0, 25)}</td>
                  <td className="px-3 py-2 border-b border-[#F0F0F0] text-slate-600">{stripHtml(q.option4_eng).substring(0, 25)}</td>
                  <td className="px-3 py-2 border-b border-[#F0F0F0] font-bold text-emerald-600">{getAnswerLabel(q)}</td>
                  <td className="px-3 py-2 border-b border-[#F0F0F0] text-slate-500">{q.subject?.substring(0, 12)}</td>
                  <td className="px-3 py-2 border-b border-[#F0F0F0]"><span className={`px-1.5 py-0.5 rounded text-[8px] font-bold ${q.difficulty === 'Easy' ? 'bg-green-50 text-green-600' : q.difficulty === 'Medium' ? 'bg-amber-50 text-amber-600' : 'bg-red-50 text-red-600'}`}>{q.difficulty}</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {questions.length > 8 && <div className="text-center py-3 text-[10px] text-slate-400 border-t border-[#F0F0F0]">+ {questions.length - 8} more rows</div>}
      </div>
    </div>
  );

  // JSON Preview
  const renderJsonPreview = () => {
    const sample = {
      title: config.testTitle, organization: config.organizationName, totalQuestions: questions.length,
      questions: questions.slice(0, 3).map((q, i) => ({
        number: i + config.startingNumber, question_eng: stripHtml(q.question_eng).substring(0, 80) + '...',
        options: { A: stripHtml(q.option1_eng).substring(0, 30), B: stripHtml(q.option2_eng).substring(0, 30), C: '...', D: '...' },
        answer: q.answer, difficulty: q.difficulty,
      })),
    };
    return (
      <div className="flex-1 overflow-auto p-6" style={{ background: '#E8EAED' }}>
        <div className="bg-[#1E293B] rounded-lg shadow-lg overflow-hidden border border-slate-700 p-5">
          <pre className="text-[11px] leading-relaxed text-emerald-400 font-mono overflow-x-auto">{JSON.stringify(sample, null, jsonPretty ? 2 : 0)}</pre>
          {questions.length > 3 && <div className="text-slate-500 text-[10px] mt-3 font-mono">  // ... + {questions.length - 3} more questions</div>}
        </div>
      </div>
    );
  };

  // Table Preview
  const renderTablePreview = () => (
    <div className="flex-1 overflow-auto p-6" style={{ background: '#E8EAED' }}>
      <div className="bg-white rounded-lg shadow-lg overflow-hidden border border-[#E5E7EB] p-6">
        <h2 className="text-lg font-bold text-slate-900 text-center mb-1">{config.testTitle}</h2>
        <p className="text-xs text-slate-500 text-center mb-4">{config.organizationName} | {questions.length} Questions | {totalMarks} Marks</p>
        <table className="w-full text-[10px] border-collapse">
          <thead><tr>
            {['#', 'Question', 'A', 'B', 'C', 'D', 'Answer'].map((h, i) => (
              <th key={i} className="px-2 py-2 text-left font-bold text-slate-500 bg-slate-50 border border-[#E5E7EB] text-[9px] uppercase">{h}</th>
            ))}
          </tr></thead>
          <tbody>
            {questions.slice(0, 6).map((q, i) => (
              <tr key={q.id} className={i % 2 === 0 ? '' : 'bg-slate-50/50'}>
                <td className="px-2 py-1.5 border border-[#E5E7EB] font-bold text-slate-400">{i + config.startingNumber}</td>
                <td className="px-2 py-1.5 border border-[#E5E7EB] text-slate-700">{stripHtml(q.question_eng).substring(0, 80)}...</td>
                <td className="px-2 py-1.5 border border-[#E5E7EB] text-slate-600">{stripHtml(q.option1_eng).substring(0, 20)}</td>
                <td className="px-2 py-1.5 border border-[#E5E7EB] text-slate-600">{stripHtml(q.option2_eng).substring(0, 20)}</td>
                <td className="px-2 py-1.5 border border-[#E5E7EB] text-slate-600">{stripHtml(q.option3_eng).substring(0, 20)}</td>
                <td className="px-2 py-1.5 border border-[#E5E7EB] text-slate-600">{stripHtml(q.option4_eng).substring(0, 20)}</td>
                <td className="px-2 py-1.5 border border-[#E5E7EB] font-bold text-emerald-600">{getAnswerLabel(q)}</td>
              </tr>
            ))}
          </tbody>
        </table>
        {questions.length > 6 && <div className="text-center py-2 text-[10px] text-slate-400">+ {questions.length - 6} more rows</div>}
      </div>
    </div>
  );

  const activeTab = FORMAT_TABS.find(t => t.id === activeFormat)!;

  return (
    <div className="fixed inset-0 z-[9998] bg-[#E8EAED] overflow-hidden flex flex-col">
      {/* Top Bar */}
      <div className="h-12 bg-white border-b border-[#E5E7EB] flex items-center justify-between px-4 shrink-0">
        <div className="flex items-center gap-3">
          <button onClick={onBack} className="flex items-center gap-1.5 text-[11px] font-medium text-slate-500 hover:text-primary transition-colors">
            <ArrowLeft size={14} /> Back
          </button>
          <div className="h-5 w-px bg-[#E5E7EB]" />
          {/* Format Tabs */}
          <div className="flex items-center gap-0.5">
            {FORMAT_TABS.map(tab => (
              <button key={tab.id} onClick={() => setActiveFormat(tab.id)}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-bold transition-all ${activeFormat === tab.id ? `${tab.bg} ${tab.color}` : 'text-slate-400 hover:bg-slate-50 hover:text-slate-600'}`}>
                <tab.icon size={13} />
                {tab.label}
              </button>
            ))}
          </div>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 text-[10px] font-bold text-slate-400">
            <span>{questions.length} Qs</span>
            <span className="text-emerald-600">{totalMarks} Marks</span>
          </div>
          <div className="h-4 w-px bg-[#E5E7EB]" />
          {(activeFormat === 'pdf' || activeFormat === 'docx' || activeFormat === 'ppt') && (
            <div className="flex items-center gap-1">
              <button onClick={() => setPreviewScale(Math.max(50, previewScale - 10))} className="p-1 rounded hover:bg-slate-100 text-slate-400"><ZoomOut size={13} /></button>
              <span className="text-[10px] font-bold text-slate-500 w-8 text-center">{previewScale}%</span>
              <button onClick={() => setPreviewScale(Math.min(150, previewScale + 10))} className="p-1 rounded hover:bg-slate-100 text-slate-400"><ZoomIn size={13} /></button>
            </div>
          )}
          <button onClick={() => handleExport(activeFormat)} disabled={isExporting}
            className={`px-4 py-1.5 rounded-lg text-white text-[11px] font-bold transition-all flex items-center gap-1.5 disabled:opacity-50 ${activeFormat === 'pdf' ? 'bg-red-500 hover:bg-red-600' : activeFormat === 'docx' ? 'bg-blue-500 hover:bg-blue-600' : activeFormat === 'ppt' ? 'bg-orange-500 hover:bg-orange-600' : activeFormat === 'csv' ? 'bg-emerald-500 hover:bg-emerald-600' : activeFormat === 'json' ? 'bg-amber-500 hover:bg-amber-600' : 'bg-violet-500 hover:bg-violet-600'}`}>
            <Download size={12} /> {isExporting ? 'Exporting...' : `Export ${activeTab.label}`}
          </button>
        </div>
      </div>

      {/* Split Layout */}
      <div className="flex-1 flex overflow-hidden">
        {/* LEFT: Settings Panel */}
        <div className="w-[300px] shrink-0 bg-white border-r border-[#E5E7EB] flex flex-col overflow-hidden">
          {(activeFormat === 'pdf' || activeFormat === 'docx') && renderDocSettings()}
          {activeFormat === 'ppt' && renderPptSettings()}
          {activeFormat === 'csv' && renderCsvSettings()}
          {activeFormat === 'json' && renderJsonSettings()}
          {activeFormat === 'table' && renderTableSettings()}

          {/* Quick export other formats */}
          <div className="p-3 border-t border-[#E5E7EB] bg-[#FAFAFA]">
            <div className="text-[9px] font-bold text-slate-400 mb-1.5 uppercase tracking-wider">Quick Export</div>
            <div className="grid grid-cols-3 gap-1">
              {FORMAT_TABS.filter(t => t.id !== activeFormat).map(t => (
                <button key={t.id} onClick={() => handleExport(t.id)} disabled={isExporting}
                  className="py-1.5 rounded bg-[#F0F0F0] text-[9px] font-bold text-slate-500 hover:bg-slate-200 flex items-center justify-center gap-1 disabled:opacity-50">
                  <t.icon size={10} className={t.color} /> {t.label}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* RIGHT: Preview */}
        {(activeFormat === 'pdf' || activeFormat === 'docx') && renderDocPreview()}
        {activeFormat === 'ppt' && renderPptPreview()}
        {activeFormat === 'csv' && renderCsvPreview()}
        {activeFormat === 'json' && renderJsonPreview()}
        {activeFormat === 'table' && renderTablePreview()}
      </div>
    </div>
  );
};
