"use client";

import React, { useState } from 'react';
import { FileText, MonitorPlay, Download, Settings, ChevronRight, Check, X, FileJson, Layout } from 'lucide-react';
import { Question } from '../types';
import { generateQuestionSetPDF, PDFTemplate } from '../utils/pdfGenerator';
import { generateQuestionSetPPT } from '../utils/pptGenerator';

interface SetWizardProps {
    isOpen: boolean;
    onClose: () => void;
    selectedQuestions: Question[];
    onClearSelection: () => void;
}

export const SetWizard: React.FC<SetWizardProps> = ({
    isOpen,
    onClose,
    selectedQuestions,
    onClearSelection
}) => {
    const [step, setStep] = useState<'config' | 'export'>('config');
    const [setMetadata, setSetMetadata] = useState({
        title: '',
        description: '',
        exam: '',
        duration: 60
    });

    const [exportFormat, setExportFormat] = useState<'pdf' | 'ppt'>('pdf');
    const [pdfOptions, setPdfOptions] = useState({
        template: 'exam_paper' as PDFTemplate,
        includeAnswerKey: true,
        includeExplanations: false
    });
    const [pptOptions, setPptOptions] = useState({
        theme: 'dark' as 'dark' | 'light' | 'colorful',
        showAnswerAfterEach: true
    });
    const [isExporting, setIsExporting] = useState(false);

    if (!isOpen) return null;

    const handleExport = async () => {
        if (!setMetadata.title) return alert("Please enter a set title");
        setIsExporting(true);

        try {
            if (exportFormat === 'pdf') {
                await generateQuestionSetPDF(selectedQuestions, {
                    template: pdfOptions.template,
                    title: setMetadata.title,
                    subtitle: `${setMetadata.exam} • ${setMetadata.duration} Mins • ${selectedQuestions.length} Questions`,
                    includeAnswerKey: pdfOptions.includeAnswerKey,
                    includeExplanations: pdfOptions.includeExplanations,
                    footerText: 'Generated by Q-Bank Pro'
                });
            } else {
                await generateQuestionSetPPT(selectedQuestions, {
                    title: setMetadata.title,
                    subtitle: setMetadata.description || setMetadata.exam,
                    theme: pptOptions.theme,
                    showAnswerAfterEach: pptOptions.showAnswerAfterEach
                });
            }
            onClose();
            onClearSelection();
        } catch (error) {
            console.error("Export Failed:", error);
            alert("Failed to export. Please try again.");
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4 animate-in fade-in duration-200">
            <div className="bg-white rounded-2xl w-full max-w-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
                {/* Header */}
                <div className="bg-slate-50 border-b border-slate-200 p-6 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center text-white shadow-lg shadow-indigo-200">
                            <Settings size={20} />
                        </div>
                        <div>
                            <h3 className="text-lg font-black text-slate-900 uppercase tracking-tight">Set Architect</h3>
                            <p className="text-xs text-slate-500 font-medium">Configure and export your question set</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="text-slate-400 hover:text-slate-600 transition-all p-2 hover:bg-slate-100 rounded-lg">
                        <X size={20} />
                    </button>
                </div>

                {/* Content */}
                <div className="flex-1 overflow-y-auto p-6 space-y-8">
                    {/* Step 1: Configuration */}
                    <div className="space-y-4">
                        <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-1">Set Details</label>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <input
                                type="text"
                                placeholder="Set Title (e.g. Weekly Current Affairs Test)"
                                value={setMetadata.title}
                                onChange={e => setSetMetadata({ ...setMetadata, title: e.target.value })}
                                className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold text-slate-700 outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 col-span-2"
                            />
                            <input
                                type="text"
                                placeholder="Target Exam (e.g. UPSC Prelims)"
                                value={setMetadata.exam}
                                onChange={e => setSetMetadata({ ...setMetadata, exam: e.target.value })}
                                className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold text-slate-700 outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
                            />
                            <input
                                type="number"
                                placeholder="Duration (Mins)"
                                value={setMetadata.duration}
                                onChange={e => setSetMetadata({ ...setMetadata, duration: parseInt(e.target.value) })}
                                className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold text-slate-700 outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
                            />
                        </div>
                    </div>

                    <div className="border-t border-slate-100 pt-6 space-y-4">
                        <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-1">Export Format</label>

                        <div className="grid grid-cols-2 gap-4">
                            {/* PDF Option */}
                            <button
                                onClick={() => setExportFormat('pdf')}
                                className={`p-4 rounded-xl border-2 transition-all flex flex-col items-center gap-2 ${exportFormat === 'pdf'
                                        ? 'border-indigo-500 bg-indigo-50 text-indigo-700'
                                        : 'border-slate-100 bg-slate-50 text-slate-500 hover:border-slate-200'
                                    }`}
                            >
                                <FileText size={24} />
                                <span className="text-xs font-black uppercase">Document (PDF)</span>
                            </button>

                            {/* PPT Option */}
                            <button
                                onClick={() => setExportFormat('ppt')}
                                className={`p-4 rounded-xl border-2 transition-all flex flex-col items-center gap-2 ${exportFormat === 'ppt'
                                        ? 'border-orange-500 bg-orange-50 text-orange-700'
                                        : 'border-slate-100 bg-slate-50 text-slate-500 hover:border-slate-200'
                                    }`}
                            >
                                <MonitorPlay size={24} />
                                <span className="text-xs font-black uppercase">Presentation (PPT)</span>
                            </button>
                        </div>
                    </div>

                    {/* Export Settings */}
                    <div className="border-t border-slate-100 pt-6 space-y-4">
                        <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-1">
                            {exportFormat === 'pdf' ? 'PDF Configuration' : 'PPT Configuration'}
                        </label>

                        <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-4">
                            {exportFormat === 'pdf' ? (
                                <>
                                    <div className="space-y-2">
                                        <span className="text-xs font-bold text-slate-600 block">Template Style</span>
                                        <select
                                            value={pdfOptions.template}
                                            onChange={(e) => setPdfOptions({ ...pdfOptions, template: e.target.value as PDFTemplate })}
                                            className="w-full p-2 rounded-lg border border-slate-200 text-sm font-medium"
                                        >
                                            <option value="exam_paper">Exam Paper (Standard)</option>
                                            <option value="practice_sheet">Practice Sheet (Compact)</option>
                                            <option value="workbook">Workbook (Work Space)</option>
                                            <option value="flashcards">Flashcards (Printable)</option>
                                            <option value="answer_key">Answer Key Only</option>
                                        </select>
                                    </div>
                                    <div className="flex gap-4">
                                        <label className="flex items-center gap-2 text-sm font-medium text-slate-700">
                                            <input
                                                type="checkbox"
                                                checked={pdfOptions.includeAnswerKey}
                                                onChange={e => setPdfOptions({ ...pdfOptions, includeAnswerKey: e.target.checked })}
                                                className="rounded text-indigo-600"
                                            />
                                            Include Answer Key
                                        </label>
                                        <label className="flex items-center gap-2 text-sm font-medium text-slate-700">
                                            <input
                                                type="checkbox"
                                                checked={pdfOptions.includeExplanations}
                                                onChange={e => setPdfOptions({ ...pdfOptions, includeExplanations: e.target.checked })}
                                                className="rounded text-indigo-600"
                                            />
                                            Include Explanations
                                        </label>
                                    </div>
                                </>
                            ) : (
                                <>
                                    <div className="space-y-2">
                                        <span className="text-xs font-bold text-slate-600 block">Color Theme</span>
                                        <div className="flex gap-3">
                                            {['dark', 'light', 'colorful'].map((t) => (
                                                <button
                                                    key={t}
                                                    onClick={() => setPptOptions({ ...pptOptions, theme: t as any })}
                                                    className={`px-4 py-2 rounded-lg text-xs font-bold uppercase border-2 transition-all ${pptOptions.theme === t
                                                            ? 'border-orange-500 text-orange-600 bg-white'
                                                            : 'border-transparent bg-slate-200 text-slate-500'
                                                        }`}
                                                >
                                                    {t}
                                                </button>
                                            ))}
                                        </div>
                                    </div>
                                    <label className="flex items-center gap-2 text-sm font-medium text-slate-700 mt-4">
                                        <input
                                            type="checkbox"
                                            checked={pptOptions.showAnswerAfterEach}
                                            onChange={e => setPptOptions({ ...pptOptions, showAnswerAfterEach: e.target.checked })}
                                            className="rounded text-orange-600"
                                        />
                                        Reveal Answer After Each Slide
                                    </label>
                                </>
                            )}
                        </div>
                    </div>
                </div>

                {/* Footer */}
                <div className="p-6 border-t border-slate-200 bg-slate-50 flex items-center justify-between">
                    <div className="text-xs font-bold text-slate-500">
                        {selectedQuestions.length} Questions Selected
                    </div>
                    <button
                        onClick={handleExport}
                        disabled={isExporting}
                        className="h-12 px-8 bg-indigo-600 text-white rounded-xl font-black uppercase tracking-wider hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-200 flex items-center gap-2 disabled:opacity-50"
                    >
                        {isExporting ? (
                            <>
                                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                Generating...
                            </>
                        ) : (
                            <>
                                <Download size={18} />
                                Export {exportFormat.toUpperCase()}
                            </>
                        )}
                    </button>
                </div>
            </div>
        </div>
    );
};

