import { Question } from '../types';

export interface PPTOptions {
    title: string;
    subtitle: string;
    theme: 'dark' | 'light' | 'colorful';
    showAnswerAfterEach: boolean;
    includeExplanations?: boolean;
    authorName?: string;
}

function stripHtml(html: string): string {
    if (!html) return '';
    return html.replace(/<[^>]*>/g, '').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').trim();
}

function getCorrectAnswerLabel(q: Question): string {
    const idx = parseInt(q.answer);
    if (isNaN(idx) || idx < 1 || idx > 5) return q.answer || '—';
    return String.fromCharCode(64 + idx);
}

function getCorrectAnswerText(q: Question): string {
    const idx = parseInt(q.answer);
    const optMap: Record<number, string> = {
        1: q.option1_eng, 2: q.option2_eng, 3: q.option3_eng, 4: q.option4_eng, 5: q.option5_eng || ''
    };
    return stripHtml(optMap[idx] || '');
}

function loadPptxGenJS(): Promise<any> {
    return new Promise((resolve, reject) => {
        if (typeof window !== 'undefined' && (window as any).PptxGenJS) {
            resolve((window as any).PptxGenJS);
            return;
        }
        const script = document.createElement('script');
        script.src = 'https://cdn.jsdelivr.net/gh/gitbrent/PptxGenJS@3.12.0/dist/pptxgen.bundle.js';
        script.onload = () => resolve((window as any).PptxGenJS);
        script.onerror = () => reject(new Error('Failed to load PptxGenJS'));
        document.head.appendChild(script);
    });
}

export async function generateQuestionSetPPT(questions: Question[], options: PPTOptions) {
    const PptxGenJS = await loadPptxGenJS();
    const pptx = new PptxGenJS();

    const isDark = options.theme === 'dark';
    const bgColor = isDark ? '1E293B' : 'FFFFFF';
    const textColor = isDark ? 'F1F5F9' : '1E293B';
    const mutedColor = isDark ? '94A3B8' : '6B7280';
    const accentColor = 'FF5A1F';

    pptx.layout = 'LAYOUT_WIDE';
    pptx.author = 'Q-Bank Pro';
    pptx.title = options.title;

    // --- Title Slide ---
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: bgColor };
    titleSlide.addText(options.title, {
        x: 0.8, y: 2.0, w: 11.5, h: 1.2,
        fontSize: 36, bold: true, color: textColor, fontFace: 'Arial'
    });
    titleSlide.addText(options.subtitle || `${questions.length} Questions`, {
        x: 0.8, y: 3.2, w: 11.5, h: 0.6,
        fontSize: 16, color: mutedColor, fontFace: 'Arial'
    });
    titleSlide.addText('Generated by Q-Bank', {
        x: 0.8, y: 6.5, w: 11.5, h: 0.4,
        fontSize: 10, color: mutedColor, fontFace: 'Arial'
    });

    // --- Question Slides ---
    questions.forEach((q, index) => {
        const questionText = stripHtml(q.question_eng);
        const opts = [
            { label: 'A', text: stripHtml(q.option1_eng) },
            { label: 'B', text: stripHtml(q.option2_eng) },
            { label: 'C', text: stripHtml(q.option3_eng) },
            { label: 'D', text: stripHtml(q.option4_eng) },
        ].filter(o => o.text);
        if (q.option5_eng) opts.push({ label: 'E', text: stripHtml(q.option5_eng) });

        // Question slide
        const qSlide = pptx.addSlide();
        qSlide.background = { color: bgColor };

        // Question number badge
        qSlide.addText(`Q${index + 1}`, {
            x: 0.5, y: 0.3, w: 0.8, h: 0.5,
            fontSize: 14, bold: true, color: 'FFFFFF', fill: { color: accentColor },
            align: 'center', valign: 'middle', fontFace: 'Arial',
            rectRadius: 0.1
        });

        // Question text
        qSlide.addText(questionText, {
            x: 0.5, y: 1.0, w: 12.0, h: 1.5,
            fontSize: 20, color: textColor, fontFace: 'Arial',
            valign: 'top', wrap: true
        });

        // Options grid (2x2)
        const optColors = ['3B82F6', '8B5CF6', 'F59E0B', '10B981', 'EC4899'];
        opts.forEach((opt, oi) => {
            const col = oi % 2;
            const row = Math.floor(oi / 2);
            const x = 0.5 + col * 6.2;
            const y = 3.0 + row * 1.6;

            qSlide.addShape(pptx.ShapeType.roundRect, {
                x, y, w: 5.8, h: 1.3,
                fill: { color: isDark ? '334155' : 'F9FAFB' },
                line: { color: isDark ? '475569' : 'E5E7EB', width: 1 },
                rectRadius: 0.15
            });

            qSlide.addText(`${opt.label})`, {
                x: x + 0.2, y, w: 0.5, h: 1.3,
                fontSize: 14, bold: true, color: optColors[oi] || accentColor,
                fontFace: 'Arial', valign: 'middle'
            });

            qSlide.addText(opt.text, {
                x: x + 0.7, y, w: 4.8, h: 1.3,
                fontSize: 14, color: textColor, fontFace: 'Arial',
                valign: 'middle', wrap: true
            });
        });

        // Footer
        qSlide.addText(`${index + 1} / ${questions.length}`, {
            x: 11.5, y: 7.0, w: 1.5, h: 0.4,
            fontSize: 10, color: mutedColor, fontFace: 'Arial', align: 'right'
        });

        // Answer slide (if showAnswerAfterEach)
        if (options.showAnswerAfterEach) {
            const aSlide = pptx.addSlide();
            aSlide.background = { color: bgColor };

            aSlide.addText(`Q${index + 1} — Answer`, {
                x: 0.5, y: 0.3, w: 3, h: 0.5,
                fontSize: 14, bold: true, color: 'FFFFFF', fill: { color: '22C55E' },
                align: 'center', valign: 'middle', fontFace: 'Arial', rectRadius: 0.1
            });

            aSlide.addText(questionText, {
                x: 0.5, y: 1.0, w: 12.0, h: 1.2,
                fontSize: 16, color: mutedColor, fontFace: 'Arial', wrap: true
            });

            aSlide.addText(`Correct Answer: ${getCorrectAnswerLabel(q)}) ${getCorrectAnswerText(q)}`, {
                x: 0.5, y: 2.8, w: 12.0, h: 1.0,
                fontSize: 22, bold: true, color: '22C55E', fontFace: 'Arial'
            });

            const sol = stripHtml(q.solution_eng);
            if (sol) {
                aSlide.addText(sol, {
                    x: 0.5, y: 4.2, w: 12.0, h: 2.5,
                    fontSize: 13, color: textColor, fontFace: 'Arial',
                    valign: 'top', wrap: true
                });
            }
        }
    });

    // --- Summary Slide (if not showing answers after each) ---
    if (!options.showAnswerAfterEach) {
        const sumSlide = pptx.addSlide();
        sumSlide.background = { color: bgColor };
        sumSlide.addText('Answer Key', {
            x: 0.5, y: 0.3, w: 3, h: 0.6,
            fontSize: 24, bold: true, color: textColor, fontFace: 'Arial'
        });

        const answerRows = questions.map((q, i) =>
            `Q${i + 1}: ${getCorrectAnswerLabel(q)}`
        );

        // Split into columns of 15
        const cols = [];
        for (let i = 0; i < answerRows.length; i += 15) {
            cols.push(answerRows.slice(i, i + 15));
        }

        cols.forEach((col, ci) => {
            sumSlide.addText(col.join('\n'), {
                x: 0.5 + ci * 3.2, y: 1.2, w: 3.0, h: 6.0,
                fontSize: 14, color: textColor, fontFace: 'Arial', valign: 'top',
                lineSpacingMultiple: 1.4
            });
        });
    }

    // Download
    await pptx.writeFile({ fileName: `${options.title.replace(/[^a-zA-Z0-9]/g, '_')}_${new Date().toISOString().split('T')[0]}.pptx` });
}
